[Appearance]
color_scheme_path=/home/user/.config/qt5ct/style-colors.conf
custom_palette=true
icon_theme=breeze-dark
standard_dialogs=gtk3
style=kvantum-dark

[Fonts]
fixed="MesloLGS Nerd Font Mono,12,-1,5,50,0,0,0,0,0,Regular"
general="MesloLGS Nerd Font,12,-1,5,50,0,0,0,0,0,Regular"

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\xff\xff\xff\xf5\xff\xff\xff\xcf\0\0\x3\xbc\0\0\x3\xec\0\0\0\0\0\0\0\0\0\0\x3\xb1\0\0\x3\xe1\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3\xb1\0\0\x3\xe1)
