[Appearance]
custom_palette=false
#custom_palette=true
#color_scheme_path=/home/user/.config/qt5ct/style-colors.conf
icon_theme=gnome
standard_dialogs=gtk3
#style=Adwaita-Dark
style=Breeze

[Fonts]
fixed="MesloLGS Nerd Font Mono,12,-1,5,50,0,0,0,0,0,Regular"
general="MesloLGS Nerd Font,12,-1,5,50,0,0,0,0,0,Regular"
