apt = [
    "imaginer",
    "lmstudio",
    "ollama",
    "ollama-docs",
    "fortunecraft",
    "upscayl-bin",
]

arch = [
    "imaginer",
    "lmstudio",
    "ollama",
    "ollama-docs",
    "fortunecraft",
    "upscayl-bin",
]

