arch = [
    "ardour",
    "audacity",
    "blender",
    "calibre",
    "cantata",
    "cider",
    "electrum",
    "freecad",
    "freetube",
    "furnace",
    "glaxnimate",
    "gphoto2",
    "gimp",
    "inkscape",
    "kdenlive",
    "kicad",
    "libreoffice",
    "lmms",
    "ngspice",
    "obs-studio",
    "openscad",
    "reaper",
    "spotify",
]