apt = [
    "ardour",
    "audacity",
    "blender",
    "calibre",
    "cantata",
    "drawing",
    "electrum",
    "focuswriter",
    "foliate",
    "freecad",
    "freemind-bin",
    "freetube-bin",
    "fritzing",
    "furnace",
    "gimp",
    "inkscape",
    "kdenlive",
    "kicad",
    "kicad-library",
    "kiwix-desktop",
    "kiwix-tools",
    "libreoffice-still",
    "lmms",
    "logisim-evolution-bin",
    "ngspice",
    "obs-studio",
    "openscad",
    "reaper",
    "shortwave",
    "spotify",
]

arch = [
    "ardour",
    "audacity",
    "blender",
    "calibre",
    "cantata",
    "drawing",
    "electrum",
    "focuswriter",
    "foliate",
    "freecad",
    "freemind-bin",
    "freetube-bin",
    "fritzing",
    "furnace",
    "gimp",
    "inkscape",
    "kdenlive",
    "kicad",
    "kicad-library",
    "kiwix-desktop",
    "kiwix-tools",
    "libreoffice-still",
    "lmms",
    "logisim-evolution-bin",
    "ngspice",
    "obs-studio",
    "openscad",
    "reaper",
    "shortwave",
    "spotify",
]

