arch = {
  packages = [
    "arandr",
    "barrier",
    "barrier-headless",
    "brightnessctl",
    "bspwm",
    "conky",
    "dunst",
    "eject-applet",
    "evtest",
    "eww",
    "gnome-disk-utility",
    "gxmessage",
    "imwheel",
    "lightdm",
    "lightdm-gtk-greeter",
    "menumaker",
    "mission-center",
    "ncpamixer",
    "network-manager-applet",
    "nitrogen",
    "numlockx",
    "pa-applet-git",
    "paprefs",
    "pasystray",
    "pavucontrol",
    "picom",
    "polybar",
    "stumpwm",
    "stumpwm-contrib",
    "sxhkd",
    "sysstat",
    "tint2",
    "unclutter",
    "wmctrl",
    "wmname",
    "x2x-git",
    "xautolock",
    "xdg-desktop-portal-gnome",
    "xfce4-power-manager",
    "xorg-xbacklight",
    "xorg-xinit",
    "xorg-xinput",
    "xorg-xkbcomp",
    "xorg-xkill",
    "xorg-xmodmap",
    "xorg-xprop",
    "xorg-xset",
    "xorg-xwininfo",
    "xplanet",
    "xprintidle",
    "xscreensaver",
    "xscreensaver-aerial",
    "libglade",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/nullman/packages",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "arandr",
    "barrier",
    "brightnessctl",
    "bspwm",
    "conky",
    "dunst",
    "evtest",
    "gnome-disk-utility",
    "gxmessage",
    "imwheel",
    "lightdm",
    "lightdm-gtk-greeter",
    "menumaker",
    "mission-center",
    "ncpamixer",
    "nitrogen",
    "numlockx",
    "pa-applet-git",
    "paprefs",
    "pasystray",
    "pavucontrol",
    "picom",
    "polybar",
    "stumpwm",
    "stumpwm-contrib",
    "sxhkd",
    "sysstat",
    "tint2",
    "unclutter",
    "wmctrl",
    "wmname",
    "x2x-git",
    "xautolock",
    "xdg-desktop-portal-gnome",
    "xfce4-power-manager",
    "xorg-xbacklight",
    "xorg-xinit",
    "xorg-xinput",
    "xorg-xkbcomp",
    "xorg-xkill",
    "xorg-xmodmap",
    "xorg-xprop",
    "xorg-xrandr",
    "xorg-xset",
    "xorg-xwininfo",
    "xplanet",
    "xprintidle",
    "xscreensaver",
    "xscreensaver-aerial",
    "xscreensaver-extras",
    "xscreensaver-gl-base",
    "xscreensaver-gl-extras",
    "libglade",
  ]
}

