arch = [
    "alacritty",
    "aspell-en",
    "base",
    "base-devel",
    "btop",
    "debugedit",
    "efibootmgr",
    "emacs",
    "git",
    "grub",
    "gst-plugin-pipewire",
    "htop",
    "iftop",
    "intel-media-driver",
    "intel-ucode",
    "ispell",
    "iwd",
    "keychain",
    "languagetool",
    "libpulse",
    "libva-intel-driver",
    "linux",
    "linux-headers",
    "lsb-release",
    "man-db",
    "man-pages",
    "metapac",
    "nano",
    "networkmanager",
    "nmap",
    "openssl",
    "orpie",
    "os-prober",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "pkgfile",
    "plocate",
    "python",
    "python-pip",
    "rsync",
    "rxvt-unicode",
    "screen",
    "scrot",
    "smartmontools",
    "stow",
    "sxhkd",
    "terminus-font",
    "tmux",
    "tmux-plugin-manager",
    "usbutils",
    "vim",
    "vulkan-intel",
    "wget",
    "wireless_tools",
    "wireplumber",
    "xdg-utils",
    "yay",
]