arch = [
    "alacritty",
    "base",
    "base-devel",
    "coreutils",
    "curl",
    "efibootmgr",
    "git",
    "gst-plugin-pipewire",
    "intel-media-driver",
    "intel-ucode",
    "iwd",
    "libpulse",
    "libva-intel-driver",
    "linux",
    "linux-headers",
    "metapac",
    "nano",
    "networkmanager",
    "openssl",
    "os-prober",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "pkgfile",
    "plocate",
    "python",
    "python-pip",
    "rsync",
    "rxvt-unicode",
    "smartmontools",
    "stow",
    "terminus-font",
    "usbutils",
    "vim",
    "vulkan-intel",
    "wget",
    "wireless_tools",
    "wireplumber",
    "xdg-utils",
    "yay",
]