arch = {
  packages = [
    "arandr",
    "barrier",
    "barrier-headless",
    "blueman",
    "brightnessctl",
    "bspwm",
    "conky",
    "dunst",
    "eject-applet",
    "evtest",
    "eww",
    "gconf",
    "gksu",
    "gnome-disk-utility",
    "gnome-icon-theme",
    "gnome-icon-theme-extras",
    "gnome-icon-theme-symbolic",
    "gnome-keyring",
    "gtk-engines",
    "gxmessage",
    "imwheel",
    "lightdm",
    "lightdm-gtk-greeter",
    "menumaker",
    "mission-center",
    "ncpamixer",
    "network-manager-applet",
    "nitrogen",
    "numlockx",
    "pa-applet-git",
    "paprefs",
    "pasystray",
    "pavucontrol",
    "picom",
    "polkit",
    "polybar",
    "stumpwm",
    "stumpwm-contrib",
    "sxhkd",
    "sysstat",
    "tint2",
    "unclutter",
    "wmctrl",
    "wmname",
    "x2x-git",
    "xautolock",
    "xdg-desktop-portal-gnome",
    "xfce4-power-manager",
    "xorg-xbacklight",
    "xorg-xinit",
    "xorg-xinput",
    "xorg-xkbcomp",
    "xorg-xkill",
    "xorg-xmodmap",
    "xorg-xprop",
    "xorg-xrandr",
    "xorg-xset",
    "xorg-xwininfo",
    "xplanet",
    "xprintidle",
    "xscreensaver",
    "xscreensaver-aerial",
    "xvkbd",
    "libgksu",
    "libglade",
    "libgnome-keyring",
  ]
}

