arch = {
  packages = [
    "alacritty",
    "archlinux-keyring",
    "base",
    "base-devel",
    "coreutils",
    "curl",
    "efibootmgr",
    "git",
    "go",
    "gst-plugin-pipewire",
    "gum",
    "inetutils",
    "intel-media-driver",
    "intel-ucode",
    "iwd",
    "less",
    "libpulse",
    "libva-intel-driver",
    "linux",
    "linux-firmware",
    "linux-headers",
    "lsof",
    "man-db",
    "man-pages",
    "metapac",
    "mkinitcpio",
    "nano",
    "networkmanager",
    "openssl",
    "os-prober",
    "pacman-contrib",
    "paru",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "pkgfile",
    "plocate",
    "python",
    "python-urllib3",
    "rsync",
    "rust",
    "rxvt-unicode",
    "smartmontools",
    "stow",
    "sudo",
    "terminus-font",
    "usbutils",
    "vim",
    "vulkan-intel",
    "wget",
    "wireless_tools",
    "wireplumber",
    "wpa_supplicant",
    "xdg-utils",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "alacritty",
    "coreutils",
    "curl",
    "efibootmgr",
    "git",
    "golang",
    "gum",
    "intel-media-driver",
    "less",
    "libva-intel-driver",
    "linux-firmware",
    "lsof",
    "man-db",
    "man-pages",
    "metapac",
    "nano",
    "NetworkManager",
    "openssl",
    "os-prober",
    "plocate",
    "python3",
    "rsync",
    "rust",
    "smartmontools",
    "stow",
    "sudo",
    "terminus-fonts",
    "usbutils",
    "wget2-wget",
    "wpa_supplicant",
    "xdg-utils",
  ]
}

