arch = [
    "argc",
    "asciinema",
    "bat",
    "bc",
    "bitwarden-cli",
    "bitwarden-menu",
    "bitwarden-rofi",
    "boxes",
    "broot",
    "calcurse",
    "chezmoi",
    "cp437",
    "cpuburn",
    "daktilo",
    "ddgr",
    "devtoolbox",
    "dict",
    "diskonaut",
    "element",
    "exa",
    "f3",
    "fd",
    "file-roller",
    "frogmouth",
    "gcalcli",
    "gdu",
    "gdu",
    "googler",
    "gpart",
    "hardinfo",
    "hdparm",
    "hexedit",
    "hexyl",
    "hq",
    "hyperfine",
    "id3v2",
    "inetutils",
    "intel-gpu-tools",
    "jq",
    "lsd",
    "mesa-utils",
    "miller",
    "minicom",
    "mtr",
    "navi",
    "ncdu",
    "nodejs-how2",
    "ookla-speedtest",
    "powertop",
    "procs",
    "rar",
    "remind",
    "ripgrep",
    "sad",
    "sd",
    "sendmail",
    "sharutils",
    "smem",
    "speedtest-cli",
    "stress",
    "sttr",
    "superfile-bin",
    "sysbench",
    "sysstat",
    "sysz",
    "testdisk",
    "textual-paint",
    "thefuck",
    "timidity++",
    "tokei",
    "translate-shell",
    "ugrep",
    "units",
    "wipe",
    "xplr",
    "yq",
    "yt-dlp",
    "zenith-bin",
    "zoxide",
]