arch = {
  packages = [
    "asciinema",
    "bat",
    "bc",
    "broot",
    "chezmoi",
    "daktilo",
    "ddgr",
    "diskonaut",
    "dysk",
    "element",
    "fd",
    "file-roller",
    "gdu",
    "glmark2",
    "gpart",
    "gping",
    "hardinfo2",
    "hdparm",
    "hyperfine",
    "id3v2",
    "intel-gpu-tools",
    "lsd",
    "mesa-utils",
    "miller",
    "minicom",
    "mtr",
    "navi",
    "perl-image-exiftool",
    "picocom",
    "procs",
    "sad",
    "sd",
    "sharutils",
    "speedtest-cli",
    "stress",
    "sysbench",
    "testdisk",
    "timidity++",
    "translate-shell",
    "yt-dlp",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/nullman/packages",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "alpine",
    "asciinema",
    "bat",
    "bc",
    "boxes",
    "chezmoi",
    "croc",
    "ddgr",
    "diskonaut",
    "f3",
    "gdu",
    "ghostscript",
    "glmark2",
    "googler",
    "gpart",
    "hardinfo2",
    "hdparm",
    "hyperfine",
    "id3v2",
    "lsd",
    "miller",
    "minicom",
    "navi",
    "ocrmypdf",
    "pandoc-pdf",
    "phoronix-test-suite",
    "picocom",
    "procs",
    "sad",
    "sendmail",
    "sharutils",
    "smem",
    "speedtest-cli",
    "stress",
    "sysbench",
    "testdisk",
    "thefuck",
    "timidity++",
    "translate-shell",
    "units",
    "yt-dlp",
    "zoxide",
    "pandoc-cli",
    "perl-Image-ExifTool",
  ]
}

