arch = [
    "aalib",
    "asciiquarium",
    "bullshit",
    "cbonsai",
    "cmatrix",
    "cowsay",
    "figlet",
    "genact",
    "hacker-typer",
    "hollywood",
    "lolcat",
    "rig",
    "sl",
]