arch = [
    "acme",
    "adb-sync-git",
    "android-studio",
    "android-tools",
    "android-udev",
    "autoconf",
    "automake",
    "binutils",
    "binutils-ia16",
    "bison",
    "c3-lsp",
    "c3c",
    "cc65",
    "ccache",
    "clang",
    "cmake",
    "code",
    "csvkit",
    "ctags",
    "dbeaver",
    "flex",
    "fpc",
    "gcc",
    "gcc-ia16",
    "github-desktop",
    "glibc",
    "gmp",
    "gnuplot",
    "go",
    "gpp",
    "gradle",
    "gradle-doc",
    "graphviz",
    "hq",
    "htmlq",
    "intellij-idea-community-edition",
    "ipython",
    "jdk-openjdk",
    "jq",
    "jqp",
    "jre",
    "kotlin",
    "lazarus",
    "lazarus-qt6",
    "lazygit",
    "lazyjournal",
    "libedit",
    "libmpc",
    "m4",
    "mpfr",
    "nasm",
    "openwatcom-v2",
    "pandoc-bin",
    "patch",
    "perl-lwp-protocol-https",
    "perl-text-aspell",
    "plantuml",
    "pup",
    "qt5-tools",
    "qt6-tools",
    "racket",
    "regina-rexx",
    "ruby",
    "ruby-lsp",
    "rust",
    "shellcheck",
    "swift-bin",
    "texlive-full",
    "tokei",
    "vlang",
    "x16-emulator",
    "x16-rom",
    "yq",
    "zlib",
]