arch = [
    "acme",
    "adb-sync",
    "amber-lang",
    "android-studio",
    "android-tools",
    "android-udev-rules",
    "autoconf",
    "automake",
    "binutils",
    "binutils-ia16",
    "bison",
    "bundix",
    "c3-lsp",
    "c3c",
    "cc65",
    "ccache",
    "clang",
    "cmake",
    "crexx",
    "csvkit",
    "ctags",
    "dbeaver-bin",
    "djgpp_i586",
    "djgpp_i686",
    "flex",
    "fpc",
    "gcc",
    "gcc-ia16",
    "github-desktop",
    "glibc",
    "gmp",
    "gnumake",
    "gnuplot",
    "go",
    "gpp",
    "gradle",
    "gradle-doc",
    "graphviz",
    "htmlq",
    "ipython",
    "jdk-openjdk",
    "jetbrains.idea-community",
    "jq",
    "jqp",
    "jre",
    "kotlin",
    "lazarus",
    "lazarus-qt",
    "lazygit",
    "lazyjournal",
    "libedit",
    "libmpc",
    "m4",
    "mpfr",
    "nasm",
    "node2nix",
    "open-watcom-bin",
    "open-watcom-v2",
    "pandoc",
    "patch",
    "perl-lwp-protocol-https",
    "perl-text-aspell",
    "plantuml",
    "pup",
    "python",
    "qt5-tools",
    "qt6-tools",
    "racket",
    "regina",
    "ruby",
    "ruby-lsp",
    "rust",
    "rustc",
    "shellcheck",
    "swift",
    "texlive-full",
    "tokei",
    "vlang",
    "vscode",
    "x16-emulator",
    "x16-rom",
    "yq",
    "zlib",
]