arch = [
    "qt5-tools",
    "qt6-tools",
    "binutils",
    "ccache",
    "cmake",
    "github-desktop",
    "gradle",
    "gradle-doc",
    "ipython",
    "jdk-openjdk",
    "ruby",
    "rustup",
    "perl-lwp-protocol-https",
    "perl-text-aspell",
]