arch = {
  packages = [
    "acme",
    "android-sdk-build-tools",
    "android-sdk-platform-tools",
    "android-studio",
    "android-tools",
    "android-udev",
    "autoconf",
    "autoconf-archive",
    "automake",
    "binutils",
    "binutils-ia16",
    "bison",
    "cc65",
    "ccache",
    "clang",
    "clisp",
    "cmake",
    "code",
    "csvkit",
    "ctags",
    "dbeaver",
    "debtap",
    "deno",
    "diffutils",
    "djgpp-binutils",
    "djgpp-djcrx-bootstrap",
    "djgpp-gcc",
    "dotnet-runtime",
    "dotnet-sdk",
    "flex",
    "fpc",
    "freebasic",
    "gcc",
    "gcc12",
    "github-desktop",
    "glibc",
    "gmp",
    "gnuplot",
    "gradle",
    "gradle-doc",
    "graphviz",
    "guile",
    "htmlq",
    "intellij-idea-community-edition",
    "ipython",
    "jq",
    "jre",
    "kotlin",
    "lazarus",
    "lazarus-qt6",
    "lazygit",
    "lazyjournal",
    "libedit",
    "libmpc",
    "m4",
    "mpfr",
    "nasm",
    "openwatcom-v2",
    "pandoc-bin",
    "patch",
    "perl-lwp-protocol-https",
    "perl-text-aspell",
    "plantuml",
    "pup",
    "quicklisp",
    "racket",
    "retro68-git",
    "ruby",
    "ruby-lsp",
    "sbcl",
    "shellcheck",
    "swift-bin",
    "terminology",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-fontsrecommended",
    "texlive-latexextra",
    "texlive-plaingeneric",
    "texlive-pictures",
    "tokei",
    "vscodium",
    "yq",
    "zlib",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "android-tools",
    "autoconf",
    "autoconf-archive",
    "automake",
    "binutils",
    "bison",
    "cc65",
    "ccache",
    "chibi-scheme",
    "clang",
    "clisp",
    "cmake",
    "ctags",
    "diffutils",
    "dotnet-runtime-10.0",
    "dotnet-sdk-10.0",
    "flex",
    "fpc",
    "gcc",
    "glibc",
    "gmp",
    "gnuplot",
    "graphviz",
    "guile30",
    "java-25-openjdk",
    "jq",
    "lazarus",
    "m4",
    "mpfr",
    "multimarkdown",
    "nasm",
    "ncurses",
    "patch",
    "plantuml",
    "python3-ipython",
    "racket",
    "regina-rexx",
    "regina-rexx-doc",
    "ruby",
    "sbcl",
    "ShellCheck",
    "terminology",
    "texlive",
    "texlive-fontawesome",
    "tokei",
    "yq",
    "cairo-devel",
    "glib2-devel",
    "glibc-all-langpacks",
    "gtk4-devel",
    "lua-devel",
    "libedit",
    "libglvnd-devel",
    "libglvnd-gles",
    "libmpc",
    "ncurses-devel",
    "perl-LWP-Protocol-https",
    "perl-Text-Aspell",
    "readline-devel",
    "SDL3-devel",
  ]
}

