arch = [
    "acme",
    "android-studio",
    "android-tools",
    "android-udev",
    "autoconf",
    "automake",
    "binutils",
    "binutils-ia16",
    "bison",
    "c3-lsp",
    "c3c",
    "cc65",
    "ccache",
    "clang",
    "cmake",
    "code",
    "csvkit",
    "ctags",
    "flex",
    "texlive-bin",
    "texlive-core",
    "texlive-fontsextra",
    "texlive-latexextra",
    "texlive-pictures",
    "texlive-science",
]