dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "copr-rpmbuild",
    "fd-find",
    "fedora-bookmarks",
    "fedora-chromium-config",
    "fedora-flathub-remote",
    "fedora-release-workstation",
    "fedora-workstation-backgrounds",
    "fedora-workstation-repositories",
    "filesystem",
    "fpaste",
    "fprintd-pam",
    "gdm",
    "general-purpose-preprocessor",
    "gettext",
    "glib-networking",
    "glycin-thumbnailer",
    "gnome-backgrounds",
    "gnome-bluetooth",
    "gnome-boxes",
    "gnome-browser-connector",
    "gnome-calculator",
    "gnome-calendar",
    "gnome-characters",
    "gnome-classic-session",
    "gnome-clocks",
    "gnome-color-manager",
    "gnome-connections",
    "gnome-contacts",
    "gnome-control-center",
    "gnome-epub-thumbnailer",
    "gnome-font-viewer",
    "gnome-initial-setup",
    "gnome-logs",
    "gnome-maps",
    "gnome-remote-desktop",
    "gnome-session-wayland-session",
    "gnome-shell",
    "gnome-shell-extension-background-logo",
    "gnome-software",
    "gnome-system-monitor",
    "gnome-text-editor",
    "gnome-user-docs",
    "gnome-user-share",
    "gnome-weather",
    "gst-thumbnailers",
    "gstreamer1-plugin-dav1d",
    "gstreamer1-plugin-libav",
    "gstreamer1-plugin-openh264",
    "gstreamer1-plugins-bad-free",
    "gstreamer1-plugins-good",
    "gstreamer1-plugins-ugly-free",
    "gutenprint-cups",
    "gvfs-afc",
    "gvfs-afp",
    "gvfs-archive",
    "gvfs-fuse",
    "gvfs-goa",
    "gvfs-gphoto2",
    "gvfs-mtp",
    "hplip",
    "hyperv-daemons",
    "ibus-anthy",
    "ibus-chewing",
    "ibus-gtk3",
    "ibus-gtk4",
    "ibus-hangul",
    "ibus-libpinyin",
    "ibus-m17n",
    "ibus-typing-booster",
    "igt-gpu-tools",
    "intel-audio-firmware",
    "intel-gpu-firmware",
    "intel-lpmd",
    "intel-media-driver",
    "intel-vsc-firmware",
    "iproute",
    "iputils",
    "iwlegacy-firmware",
    "iwlwifi-dvm-firmware",
    "iwlwifi-mvm-firmware",
    "kbd",
    "kernel",
    "kernel-core",
    "kernel-devel",
    "kernel-modules",
    "kernel-modules-core",
    "kmod-nvidia-580xx-7.1.3-201.fc44.x86_64",
    "kmod-nvidia-580xx-7.1.4-200.fc44.x86_64",
    "kmod-nvidia-580xx-7.1.4-202.fc44.x86_64",
    "langpacks-en",
    "libertas-firmware",
    "libsane-hpaio",
    "libva-intel-driver",
    "libva-intel-media-driver",
    "logrotate",
    "loupe",
    "mcelog",
    "mesa-dri-drivers",
    "mesa-vulkan-drivers",
    "microcode_ctl",
    "mt7xxx-firmware",
    "nautilus",
    "NetworkManager-adsl",
    "NetworkManager-bluetooth",
    "NetworkManager-config-connectivity-fedora",
    "NetworkManager-openconnect-gnome",
    "NetworkManager-openvpn-gnome",
    "NetworkManager-ppp",
    "NetworkManager-ssh-gnome",
    "NetworkManager-vpnc-gnome",
    "NetworkManager-wifi",
    "nmap-ncat",
    "nss-mdns",
    "nxpwireless-firmware",
    "opensc",
    "PackageKit-command-not-found",
    "PackageKit-gstreamer-plugin",
    "PackageKit-gtk3-module",
    "pam_afs_session",
    "papers-nautilus",
    "passwdqc",
    "patchutils",
    "plymouth-system-theme",
    "policycoreutils-python-utils",
    "prefixdevname",
    "ptyxis",
    "qcom-wwan-firmware",
    "realmd",
    "realtek-firmware",
    "rootfiles",
    "rpm",
    "rpmfusion-free-release",
    "rpmfusion-nonfree-release",
    "rygel",
    "sssd-common",
    "sushi",
    "symlinks",
    "systemd",
    "systemd-oomd-defaults",
    "systemd-resolved",
    "systemtap",
    "tiwilink-firmware",
    "wget2-wget",
    "xdg-desktop-portal-gnome",
    "xdg-desktop-portal-gtk",
    "xdg-user-dirs-gtk",
    "yelp",
    "zram-generator",
    "librsvg2",
    "localsearch",
    "ModemManager",
    "NetworkManager-wwan",
    "plymouth",
    "policycoreutils",
    "procps-ng",
    "psacct",
    "psmisc",
    "python3-swiftclient",
    "selinux-policy-targeted",
    "setup",
    "shadow-utils",
    "shim-x64",
    "sos",
    "sssd-kcm",
    "subversion",
    "uresourced",
    "usb_modeswitch",
    "util-linux",
    "zram-generator-defaults",
  ]
}

