dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/nullman/packages",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "alternatives",
    "audit-libs",
    "bzip2-libs",
    "ca-certificates",
    "coreutils-common",
    "cracklib",
    "cracklib-dicts",
    "crypto-policies",
    "crypto-policies-scripts",
    "cryptsetup-libs",
    "cyrus-sasl-lib",
    "dbus",
    "dbus-broker",
    "dbus-common",
    "device-mapper",
    "device-mapper-libs",
    "dnf5",
    "dnf5-plugins",
    "dnf-plugins-core",
    "elfutils-debuginfod-client",
    "elfutils-default-yama-scope",
    "elfutils-libelf",
    "elfutils-libs",
    "expat",
    "fedora-gpg-keys",
    "fedora-release",
    "fedora-release-common",
    "fedora-release-identity-basic",
    "fedora-repos",
    "file-libs",
    "filesystem",
    "findutils",
    "fmt",
    "gdbm-libs",
    "glib2",
    "glibc-common",
    "glibc-gconv-extra",
    "glibc-langpack-en",
    "glibc-minimal-langpack",
    "gnulib-l10n",
    "gnupg2-dirmngr",
    "gnupg2-gpg-agent",
    "gnupg2-gpgconf",
    "gnupg2-keyboxd",
    "gnupg2-verify",
    "gnutls",
    "grep",
    "gzip",
    "haveged",
    "ima-evm-utils-libs",
    "iputils",
    "json-c",
    "kbd",
    "kbd-legacy",
    "kbd-misc",
    "keyutils-libs",
    "kmod",
    "kmod-libs",
    "krb5-libs",
    "libacl",
    "libarchive",
    "libassuan",
    "libattr",
    "libblkid",
    "libbpf",
    "libbrotli",
    "libcap",
    "libcap-ng",
    "libcbor",
    "libcom_err",
    "libcurl",
    "libdnf5",
    "libdnf5-cli",
    "libdnf5-plugin-expired-pgp-keys",
    "libeconf",
    "libevent",
    "libfdisk",
    "libffi",
    "libfido2",
    "libfsverity",
    "libgcc",
    "libgcrypt",
    "libgomp",
    "libgpg-error",
    "libidn2",
    "libksba",
    "libmodulemd",
    "libmount",
    "libnghttp2",
    "libnghttp3",
    "libpkgconf",
    "libpsl",
    "libpwquality",
    "librepo",
    "libseccomp",
    "libsecret",
    "libselinux",
    "libsepol",
    "libsmartcols",
    "libsolv",
    "libssh",
    "libssh-config",
    "libstdc++",
    "libtasn1",
    "libtool-ltdl",
    "libunistring",
    "libusb1",
    "libuuid",
    "libverto",
    "libxcrypt",
    "libxkbcommon",
    "libxml2",
    "libyaml",
    "libzstd",
    "lua-libs",
    "lz4-libs",
    "mkpasswd",
    "mpdecimal",
    "ncurses-base",
    "ncurses-libs",
    "nettle",
    "ngtcp2",
    "ngtcp2-crypto-ossl",
    "npth",
    "openldap",
    "openssl-libs",
    "p11-kit",
    "p11-kit-trust",
    "pam-libs",
    "pcre2",
    "pcre2-syntax",
    "pinentry",
    "pkcs11-provider",
    "pkgconf",
    "pkgconf-m4",
    "pkgconf-pkg-config",
    "popt",
    "publicsuffix-list-dafsa",
    "python3-libs",
    "python3-urllib3",
    "python-pip-wheel",
    "python-unversioned-command",
    "qrencode-libs",
    "readline",
    "rpm",
    "rpm-build-libs",
    "rpmfusion-free-release",
    "rpmfusion-nonfree-release",
    "rpm-libs",
    "rpm-plugin-audit",
    "rpm-sequoia",
    "rpm-sign-libs",
    "sdbus-cpp",
    "sed",
    "setup",
    "sqlite-libs",
    "systemd",
    "systemd-libs",
    "systemd-networkd",
    "systemd-pam",
    "systemd-resolved",
    "systemd-shared",
    "systemd-sysusers",
    "systemd-udev",
    "tpm2-tss",
    "tzdata",
    "util-linux-core",
    "wcurl",
    "whois-nls",
    "xkeyboard-config",
    "xterm",
    "xz-libs",
    "zchunk-libs",
    "zlib-ng-compat",
  ]
}

