dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/nullman/packages",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "abrt-desktop",
    "alternatives",
    "atril",
    "audit-libs",
    "bzip2-libs",
    "ca-certificates",
    "claws-mail",
    "claws-mail-plugins-archive",
    "claws-mail-plugins-attachwarner",
    "claws-mail-plugins-att-remover",
    "claws-mail-plugins-fetchinfo",
    "claws-mail-plugins-mailmbox",
    "claws-mail-plugins-newmail",
    "claws-mail-plugins-notification",
    "claws-mail-plugins-pgp",
    "claws-mail-plugins-rssyl",
    "claws-mail-plugins-smime",
    "claws-mail-plugins-spam-report",
    "claws-mail-plugins-tnef",
    "claws-mail-plugins-vcalendar",
    "coreutils-common",
    "cracklib",
    "cracklib-dicts",
    "crypto-policies",
    "crypto-policies-scripts",
    "cryptsetup-libs",
    "cyrus-sasl-lib",
    "dbus",
    "dbus-broker",
    "dbus-common",
    "device-mapper",
    "device-mapper-libs",
    "elfutils-debuginfod-client",
    "elfutils-default-yama-scope",
    "elfutils-libelf",
    "elfutils-libs",
    "expat",
    "fedora-gpg-keys",
    "fedora-release",
    "fedora-release-common",
    "fedora-release-identity-basic",
    "fedora-repos",
    "file-libs",
    "findutils",
    "fmt",
    "galculator",
    "gdbm-libs",
    "geany",
    "glib2",
    "glibc-common",
    "glibc-gconv-extra",
    "glibc-langpack-en",
    "glibc-minimal-langpack",
    "gnome-keyring-pam",
    "gnulib-l10n",
    "gnupg2-dirmngr",
    "gnupg2-gpg-agent",
    "gnupg2-gpgconf",
    "gnupg2-keyboxd",
    "gnupg2-verify",
    "gnutls",
    "grep",
    "greybird-dark-theme",
    "greybird-light-theme",
    "greybird-xfce4-notifyd-theme",
    "greybird-xfwm4-theme",
    "grub2-pc",
    "gtk-xfce-engine",
    "gzip",
    "ima-evm-utils-libs",
    "irssi",
    "json-c",
    "kbd-legacy",
    "kbd-misc",
    "keepassxc",
    "keyutils-libs",
    "kmod",
    "kmod-libs",
    "krb5-libs",
    "libacl",
    "libarchive",
    "libassuan",
    "libattr",
    "libblkid",
    "libbpf",
    "libbrotli",
    "libcap",
    "libcap-ng",
    "libcbor",
    "libcom_err",
    "libcurl",
    "libdnf5",
    "libdnf5-cli",
    "libdnf5-plugin-expired-pgp-keys",
    "libeconf",
    "libevent",
    "libfdisk",
    "libffi",
    "libfido2",
    "libfsverity",
    "libgcc",
    "libgcrypt",
    "libgomp",
    "libgpg-error",
    "libidn2",
    "libksba",
    "libmodulemd",
    "libmount",
    "libnghttp2",
    "libnghttp3",
    "libpkgconf",
    "libpsl",
    "libpwquality",
    "librepo",
    "libseccomp",
    "libsecret",
    "libselinux",
    "libsepol",
    "libsmartcols",
    "libsolv",
    "libssh",
    "libssh-config",
    "libstdc++",
    "libtasn1",
    "libtool-ltdl",
    "libunistring",
    "libusb1",
    "libuuid",
    "libverto",
    "libxcrypt",
    "libxkbcommon",
    "libxml2",
    "libyaml",
    "libzstd",
    "lightdm-gtk",
    "links",
    "lua-libs",
    "lynx",
    "lz4-libs",
    "mc",
    "mint-y-theme",
    "mkpasswd",
    "mousepad",
    "mpdecimal",
    "ncurses-base",
    "ncurses-libs",
    "nettle",
    "network-manager-applet",
    "NetworkManager-fortisslvpn-gnome",
    "NetworkManager-iodine-gnome",
    "NetworkManager-l2tp-gnome",
    "NetworkManager-libreswan-gnome",
    "NetworkManager-sstp-gnome",
    "NetworkManager-strongswan-gnome",
    "ngtcp2",
    "ngtcp2-crypto-ossl",
    "nm-connection-editor",
    "npth",
    "ocaml-csexp",
    "ollama",
    "openldap",
    "openssh-askpass",
    "openssl-libs",
    "p11-kit",
    "p11-kit-trust",
    "pamixer",
    "pam-libs",
    "parole",
    "pavucontrol",
    "pcre2",
    "pcre2-syntax",
    "pinentry",
    "pkcs11-provider",
    "pkgconf",
    "pkgconf-m4",
    "pkgconf-pkg-config",
    "popt",
    "pragha",
    "publicsuffix-list-dafsa",
    "python3-libs",
    "python-pip-wheel",
    "python-unversioned-command",
    "qrencode-libs",
    "qubes-artwork",
    "qubes-core-agent-thunar",
    "qubes-gui-agent-xfce",
    "qubes-kernel-vm-support",
    "ranger",
    "readline",
    "ristretto",
    "rpm-build-libs",
    "rpm-libs",
    "rpm-plugin-audit",
    "rpm-sequoia",
    "rpm-sign-libs",
    "rxvt-unicode",
    "sdbus-cpp",
    "sed",
    "shc",
    "sqlite-libs",
    "systemd-libs",
    "systemd-networkd",
    "systemd-pam",
    "systemd-shared",
    "systemd-sysusers",
    "systemd-udev",
    "torbrowser-launcher",
    "tpm2-tss",
    "transmission",
    "tzdata",
    "util-linux-core",
    "w3m",
    "wcurl",
    "whois-nls",
    "wordgrinder",
    "wpa_supplicant",
    "xarchiver",
    "xfburn",
    "xfce4-about",
    "xfce4-appfinder",
    "xfce4-clipman-plugin",
    "xfce4-datetime-plugin",
    "xfce4-dict-plugin",
    "xfce4-panel",
    "xfce4-panel-profiles",
    "xfce4-places-plugin",
    "xfce4-power-manager",
    "xfce4-pulseaudio-plugin",
    "xfce4-screenshooter-plugin",
    "xfce4-session",
    "xfce4-settings",
    "xfce4-taskmanager",
    "xfce4-terminal",
    "xfdesktop",
    "xfwm4",
    "xfwm4-themes",
    "xkeyboard-config",
    "xterm",
    "xz-libs",
    "zchunk-libs",
    "zlib-ng-compat",
  ]
}

