arch = [
    "betterbird-bin",
    "chromium",
    "ddgr",
    "elinks",
    "filezilla",
    "firefox",
    "flashplugin",
    "gnu-netcat",
    "gomuks",
    "gopherus",
    "hyperspace-bin",
    "inetutils",
    "kristall",
    "links",
    "lynx",
    "mcabber",
    "minicom",
    "mtr",
    "nyxt",
    "pepper-flash",
    "surf",
    "surfraw",
    "syncterm-src",
    "vdhcoapp-bin",
]