arch = {
  packages = [
    "brave-bin",
    "copyparty",
    "dino",
    "discord",
    "element-desktop",
    "filezilla",
    "firefox",
    "gajim",
    "magic-wormhole",
    "nheko",
    "nyxt",
    "opensnitch",
    "quassel-client",
    "quassel-core",
    "slack-desktop",
    "surfraw",
    "syncterm-git",
    "telegram-desktop",
    "thunderbird",
    "tor-browser-bin",
    "transmission-gtk",
    "tuba",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/nullman/packages",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "brave-browser",
    "brave-origin",
    "dino",
    "filezilla",
    "firefox",
    "gajim",
    "google-chrome-stable",
    "nheko",
    "pidgin",
    "quassel-client",
    "quassel-core",
    "surf",
    "surfraw",
    "telegram-desktop",
    "thunderbird",
    "transmission-gtk",
    "tuba",
    "vdhcoapp",
  ]
}

