arch = {
  packages = [
    "brave-bin",
    "brave-origin-bin",
    "bruno-bin",
    "carburetor",
    "copyparty",
    "dino",
    "discord",
    "element-desktop",
    "filezilla",
    "firefox",
    "flashplugin",
    "gajim",
    "gopherus",
    "gossip-bin",
    "hyperspace-bin",
    "kristall",
    "magic-wormhole",
    "nheko",
    "nyxt",
    "opensnitch",
    "pepper-flash",
    "pidgin",
    "quassel-client",
    "quassel-core",
    "searxng-git",
    "simplex-chat-bin",
    "slack-desktop",
    "surf",
    "surfraw",
    "syncterm-git",
    "telegram-desktop",
    "thunderbird",
    "tor-browser-bin",
    "tractor",
    "transmission-gtk",
    "tribler-bin",
    "tuba",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "brave-browser",
    "brave-origin",
    "dino",
    "filezilla",
    "firefox",
    "gajim",
    "google-chrome",
    "nheko",
    "pidgin",
    "quassel-client",
    "quassel-core",
    "surf",
    "surfraw",
    "telegram-desktop",
    "thunderbird",
    "transmission-gtk",
    "tuba",
    "vdhcoapp",
    "at-spi2-atk",
    "cyrus-sasl-plain",
    "google-chrome-canary",
  ]
}

