arch = [
    "betterbird-bin",
    "brave",
    "bruno",
    "bruno-cli",
    "carburetor",
    "dino",
    "discord",
    "element-desktop",
    "filezilla",
    "firefox",
    "flashplugin",
    "gajim",
    "gnu-netcat",
    "gopherus",
    "gossip",
    "hyperspace-bin",
    "inetutils",
    "kristall",
    "links",
    "lynx",
    "magic-wormhole",
    "nheko",
    "nyxt",
    "opensnitch",
    "pepper-flash",
    "pidgin",
    "quasselClient",
    "slack",
    "sparkleshare",
    "surf",
    "surfraw",
    "syncterm",
    "telegram-desktop",
    "thunderbird",
    "tractor",
    "tuba",
    "vdhcoapp",
]