arch = [
    "betterbird-bin",
    "bore-cli",
    "brave",
    "bruno",
    "bruno-cli",
    "carburetor",
    "ddgr",
    "dino",
    "discord",
    "element-desktop",
    "elinks",
    "filezilla",
    "filezilla",
    "firefox",
    "firefox",
    "flashplugin",
    "gajim",
    "gnu-netcat",
    "gomuks",
    "gopherus",
    "gossip",
    "hyperspace-bin",
    "inetutils",
    "kristall",
    "kristall",
    "links",
    "lynx",
    "magic-wormhole",
    "mcabber",
    "minicom",
    "mtr",
    "ncgopher",
    "nheko",
    "nyxt",
    "nyxt",
    "opensnitch",
    "opensnitch-ui",
    "pepper-flash",
    "phetch",
    "pidgin",
    "qodem",
    "quasselClient",
    "simplex-chat-desktop",
    "slack",
    "sparkleshare",
    "surf",
    "surfraw",
    "syncterm",
    "syncterm-src",
    "telegram-desktop",
    "thunderbird",
    "thunderbird",
    "tractor",
    "translate-shell",
    "transmission_4-gtk",
    "tribler",
    "tuba",
    "vdhcoapp",
    "vdhcoapp-bin",
    "webwormhole",
    "zoom-us",
]