arch = {
  packages = [
    "adw-gtk-theme",
    "adwaita-qt5-git",
    "adwaita-qt6-git",
    "audacious",
    "audacious-plugins",
    "brave-bin",
    "clipmenu",
    "cmus",
    "cool-retro-term",
    "cowsay",
    "ffmpeg",
    "figlet",
    "font-manager",
    "gnuplot",
    "graphviz",
    "lazygit",
    "lazyjournal",
    "links",
    "lynx",
    "mc",
    "mplayer",
    "mpv",
    "papers",
    "plantuml",
    "ranger",
    "speedtest-cli",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-latexextra",
    "texlive-pictures",
    "translate-shell",
    "vlc",
    "w3m",
    "wordgrinder",
    "x48ng",
    "zlib",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "adw-gtk3-theme",
    "audacious",
    "audacious-plugins",
    "brave-origin",
    "clipmenu",
    "cmus",
    "cool-retro-term",
    "cowsay",
    "ffmpeg",
    "figlet",
    "gnuplot",
    "graphviz",
    "links",
    "lynx",
    "mc",
    "mplayer",
    "mpv",
    "papers",
    "plantuml",
    "ranger",
    "speedtest-cli",
    "texlive",
    "translate-shell",
    "vlc",
    "w3m",
    "wordgrinder",
  ]
}

