arch = {
  packages = [
    "7zip",
    "aalib",
    "acme",
    "adw-gtk-theme",
    "adwaita-qt5-git",
    "adwaita-qt6-git",
    "aha",
    "alacritty",
    "android-sdk-build-tools",
    "android-sdk-platform-tools",
    "android-studio",
    "android-tools",
    "android-udev",
    "arch-wiki-docs",
    "asciiquarium",
    "aspell-en",
    "audacious",
    "audacious-plugins",
    "autoconf",
    "autoconf-archive",
    "automake",
    "balena-etcher",
    "bandwhich",
    "base",
    "base-devel",
    "binutils",
    "binutils-ia16",
    "bison",
    "bitwarden",
    "blueman",
    "bluez",
    "bluez-utils",
    "bpytop",
    "brave-bin",
    "btop",
    "bucklespring",
    "bzip2",
    "calibre",
    "cantata",
    "cc65",
    "ccache",
    "chaotic-keyring",
    "chaotic-mirrorlist",
    "chatbox-bin",
    "checksec",
    "cifs-utils",
    "clang",
    "clipmenu",
    "clisp",
    "cmake",
    "cmatrix",
    "cmus",
    "cndrvcups-lb-bin",
    "code",
    "cool-retro-term",
    "cowsay",
    "csvkit",
    "ctags",
    "cups",
    "curl",
    "dbeaver",
    "debtap",
    "debugedit",
    "deno",
    "dialog",
    "diffutils",
    "direnv",
    "discord",
    "djgpp-binutils",
    "djgpp-djcrx-bootstrap",
    "djgpp-gcc",
    "dmenu",
    "dos2unix",
    "dosbox",
    "dosfstools",
    "dotnet-runtime",
    "dotnet-sdk",
    "duf",
    "dysk",
    "easytag",
    "emacs",
    "eog",
    "ethtool",
    "evince",
    "exfatprogs",
    "expac",
    "fastfetch",
    "ffmpeg",
    "figlet",
    "firefox",
    "flex",
    "focuswriter",
    "font-manager",
    "fortunecraft",
    "fortune-mod-off",
    "fpc",
    "freebasic",
    "freetube",
    "fs-uae",
    "fs-uae-launcher",
    "fzf",
    "gajim",
    "gcc",
    "gcc-ia16",
    "genact",
    "gimp",
    "git",
    "github-desktop",
    "glibc",
    "gmp",
    "gnome-settings-daemon",
    "gnome-themes-extra",
    "gnuplot",
    "go",
    "gphoto2",
    "gradle",
    "gradle-doc",
    "graphviz",
    "grip",
    "gtk2",
    "gtk3",
    "gtk4",
    "guile",
    "gum",
    "gvfs",
    "gvfs-smb",
    "helvum",
    "hfsprogs",
    "htmlq",
    "htop",
    "hunspell-en_us",
    "id3lib",
    "id3v2",
    "iftop",
    "imagemagick",
    "inetutils",
    "inkscape",
    "intellij-idea-community-edition",
    "inxi",
    "iperf",
    "ipython",
    "irssi",
    "ispell",
    "jdk-openjdk",
    "jq",
    "jre",
    "keychain",
    "kicad",
    "kicad-library",
    "kitty",
    "kotlin",
    "languagetool",
    "lazarus",
    "lazarus-qt6",
    "lazygit",
    "lazyjournal",
    "ldns",
    "less",
    "lhasa",
    "libedit",
    "libreoffice-still",
    "libmpc",
    "links",
    "localsend",
    "lolcat",
    "lsb-release",
    "lsof",
    "lxappearance",
    "lynx",
    "m4",
    "mame",
    "man-db",
    "man-pages",
    "mc",
    "metapac",
    "moreutils",
    "mousepad",
    "mpc",
    "mpd",
    "mpdris2",
    "mpfr",
    "mplayer",
    "mpv",
    "mtools",
    "nano",
    "nasm",
    "netkit-bsd-finger",
    "net-tools",
    "nfs-utils",
    "ngspice",
    "nheko",
    "nmap",
    "nodejs-lts-jod",
    "noto-fonts",
    "noto-fonts-emoji",
    "ntfs-3g",
    "ocaml-csexp",
    "ollama",
    "ollama-docs",
    "openssl",
    "openwatcom-v2",
    "orpie",
    "pacman-contrib",
    "pamixer",
    "pandoc-bin",
    "papers",
    "paru",
    "patch",
    "perl-lwp-protocol-https",
    "perl-text-aspell",
    "picocom",
    "pingus",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "pipewire-qubes",
    "pkgfile",
    "plantuml",
    "plocate",
    "pup",
    "pysolfc",
    "python",
    "python-urllib3",
    "qmmp",
    "qt5ct",
    "qt5-tools",
    "qt6ct",
    "qt6-tools",
    "quassel-client",
    "qubes-vm-dependencies",
    "qubes-vm-recommended",
    "qubes-vm-repo",
    "qubes-vm-thunar",
    "quicklisp",
    "racket",
    "ranger",
    "remind",
    "ripgrep",
    "rofi",
    "rofimoji",
    "rpi-imager",
    "rsync",
    "ruby",
    "ruby-lsp",
    "rust",
    "rxvt-unicode",
    "samba",
    "sbcl",
    "screen",
    "scrot",
    "shellcheck",
    "shell-color-scripts-git",
    "sl",
    "slack-desktop",
    "smbclient",
    "speedtest-cli",
    "spotify",
    "stow",
    "sudo",
    "swift-bin",
    "system-config-printer",
    "terminology",
    "terminus-font",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-fontsrecommended",
    "texlive-latexextra",
    "texlive-pictures",
    "texlive-plaingeneric",
    "the_silver_searcher",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-vcs-plugin",
    "thunar-volman",
    "thunderbird",
    "tigervnc",
    "tldr",
    "tlp",
    "tmux",
    "tokei",
    "tor-browser-bin",
    "traceroute",
    "translate-shell",
    "transmission-gtk",
    "ttf-bitstream-vera",
    "ttf-dejavu",
    "ttf-inconsolata",
    "ttf-linux-libertine",
    "tty-clock",
    "tuba",
    "unifetch",
    "unipicker",
    "unison",
    "unzip",
    "usbutils",
    "vibrancy-colors",
    "vice",
    "vim",
    "vlc",
    "vlc-plugins-all",
    "vscodium",
    "w3m",
    "wget",
    "wine",
    "wine-gecko",
    "wine-mono",
    "winetricks",
    "wipe",
    "wireplumber",
    "woeusb",
    "wordgrinder",
    "x48ng",
    "xarchiver",
    "xclip",
    "xdg-utils",
    "xdo",
    "xdotool",
    "xfce4-terminal",
    "xgetres",
    "xorg-server",
    "xorg-xev",
    "xsel",
    "xterm",
    "yad",
    "ydotool",
    "yq",
    "yt-dlp",
    "zenity",
    "zip",
    "zlib",
    "libxmp",
    "pysolfc-cardsets",
    "python-attrs",
    "python-configobj",
    "python-pygame",
    "python-pysol_cards",
    "sdl2_image",
    "sdl2_mixer",
    "sdl_mixer",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/nullman/packages",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "7zip",
    "aalib",
    "adw-gtk3-theme",
    "aha",
    "alacritty",
    "android-tools",
    "asciiquarium",
    "aspell-en",
    "audacious",
    "audacious-plugins",
    "autoconf",
    "autoconf-archive",
    "automake",
    "BasiliskII",
    "binutils",
    "bison",
    "blueman",
    "bluez",
    "brave-origin",
    "btop",
    "bzip2",
    "calibre",
    "cantata",
    "cc65",
    "ccache",
    "checksec",
    "cifs-utils",
    "clang",
    "clipmenu",
    "clisp",
    "cmake",
    "cmatrix",
    "cool-retro-term",
    "cowsay",
    "ctags",
    "cups",
    "curl",
    "debugedit",
    "dialog",
    "diffutils",
    "direnv",
    "dmenu",
    "dos2unix",
    "dosbox",
    "dosfstools",
    "duf",
    "easytag",
    "emacs",
    "eog",
    "ethtool",
    "evince",
    "exfatprogs",
    "fastfetch",
    "ffmpeg",
    "figlet",
    "firefox",
    "flex",
    "focuswriter",
    "fortune-mod",
    "fpc",
    "fzf",
    "gajim",
    "gcc",
    "gimp",
    "git",
    "glibc",
    "gmp",
    "gnome-settings-daemon",
    "gnuplot",
    "golang",
    "gphoto2",
    "graphviz",
    "grip",
    "gtk2",
    "gtk3",
    "gtk4",
    "guile30",
    "gum",
    "gvfs",
    "gvfs-smb",
    "helvum",
    "htop",
    "id3lib",
    "id3v2",
    "iftop",
    "ImageMagick",
    "inkscape",
    "inxi",
    "iperf",
    "irssi",
    "ispell",
    "jq",
    "keychain",
    "kicad",
    "kicad-doc",
    "kitty",
    "lazarus",
    "ldns",
    "less",
    "lhasa",
    "libedit",
    "libreoffice",
    "libmpc",
    "links",
    "lolcat",
    "lsb-release",
    "lsof",
    "lxappearance",
    "lynx",
    "m4",
    "mame",
    "man-db",
    "man-pages",
    "mc",
    "metapac",
    "moreutils",
    "mousepad",
    "mpc",
    "mpd",
    "mpdris2",
    "mpfr",
    "mpv",
    "mtools",
    "nano",
    "nasm",
    "finger",
    "net-tools",
    "nfs-utils",
    "ngspice",
    "nheko",
    "nmap",
    "ntfs-3g",
    "ocaml-csexp",
    "ollama",
    "openssl",
    "pamixer",
    "pandoc-pdf",
    "papers",
    "patch",
    "perl-LWP-Protocol-https",
    "perl-Text-Aspell",
    "pingus",
    "pipewire",
    "pipewire-alsa",
    "pipewire-pulse",
    "pipewire-qubes",
    "plantuml",
    "plocate",
    "PySolFC",
    "python",
    "python-urllib3",
    "qmmp",
    "qt5ct",
    "qt6ct",
    "quassel-client",
    "qubes-vm-dependencies",
    "qubes-vm-recommended",
    "racket",
    "ranger",
    "remind",
    "ripgrep",
    "rofi",
    "rofimoji",
    "rpi-imager",
    "rsync",
    "ruby",
    "rust",
    "samba",
    "sbcl",
    "screen",
    "scrot",
    "shc",
    "shellcheck",
    "sl",
    "smbclient",
    "speedtest-cli",
    "stow",
    "sudo",
    "system-config-printer",
    "terminology",
    "the_silver_searcher",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-vcs-plugin",
    "thunar-volman",
    "thunderbird",
    "tigervnc",
    "tldr",
    "tlp",
    "tmux",
    "tokei",
    "torbrowser-launcher",
    "traceroute",
    "translate-shell",
    "transmission-gtk",
    "bitstream-vera-fonts-all",
    "dejavu-fonts-all",
    "google-noto-fonts-all",
    "levien-inconsolata-fonts",
    "linux-libertine-fonts-all",
    "tuba",
    "unison",
    "unzip",
    "usbutils",
    "vim",
    "vlc",
    "vlc-plugins-all",
    "w3m",
    "wget",
    "wine",
    "wine-mono",
    "winetricks",
    "wipe",
    "wireplumber",
    "wordgrinder",
    "xarchiver",
    "xclip",
    "xdg-utils",
    "xdotool",
    "xfce4-terminal",
    "xsel",
    "xterm",
    "yad",
    "ydotool",
    "yq",
    "yt-dlp",
    "zenity",
    "zip",
    "abrt-desktop",
    "adwaita-icon-theme",
    "alsa-sof-firmware",
    "alsa-utils",
    "alternatives",
    "amd-gpu-firmware",
    "asunder",
    "atheros-firmware",
    "atril",
    "audit",
    "audit-libs",
    "b43-fwcutter",
    "b43-openfwwf",
    "bash",
    "bash-completion",
    "bluez-cups",
    "brcmfmac-firmware",
    "bzip2-libs",
    "ca-certificates",
    "cirrus-audio-firmware",
    "claws-mail",
    "claws-mail-plugins-archive",
    "claws-mail-plugins-attachwarner",
    "claws-mail-plugins-att-remover",
    "claws-mail-plugins-fetchinfo",
    "claws-mail-plugins-mailmbox",
    "claws-mail-plugins-newmail",
    "claws-mail-plugins-notification",
    "claws-mail-plugins-pgp",
    "claws-mail-plugins-rssyl",
    "claws-mail-plugins-smime",
    "claws-mail-plugins-spam-report",
    "claws-mail-plugins-tnef",
    "claws-mail-plugins-vcalendar",
    "colord",
    "compat-guile18",
    "coreutils",
    "coreutils-common",
    "cracklib",
    "cracklib-dicts",
    "crypto-policies",
    "crypto-policies-scripts",
    "cryptsetup-libs",
    "cups-browsed",
    "cups-filters",
    "cups-pk-helper",
    "cyrus-sasl-lib",
    "dbus",
    "dbus-broker",
    "dbus-common",
    "default-fonts-cjk-mono",
    "default-fonts-cjk-sans",
    "default-fonts-cjk-serif",
    "default-fonts-core-emoji",
    "default-fonts-core-math",
    "default-fonts-core-mono",
    "default-fonts-core-sans",
    "default-fonts-core-serif",
    "default-fonts-other-mono",
    "default-fonts-other-sans",
    "default-fonts-other-serif",
    "device-mapper",
    "device-mapper-libs",
    "dnf5",
    "dnf5-plugins",
    "dnsmasq",
    "dosbox-staging",
    "dracut-config-rescue",
    "e2fsprogs",
    "elfutils-debuginfod-client",
    "elfutils-default-yama-scope",
    "elfutils-libelf",
    "elfutils-libs",
    "expat",
    "fedora-gpg-keys",
    "fedora-release",
    "fedora-release-common",
    "fedora-release-identity-basic",
    "fedora-repos",
    "file-libs",
    "filesystem",
    "findutils",
    "flatpak",
    "fmt",
    "fwupd",
    "galculator",
    "gdbm-libs",
    "geany",
    "ghostscript",
    "glib2",
    "glibc-common",
    "glibc-gconv-extra",
    "glibc-langpack-en",
    "glibc-minimal-langpack",
    "gnome-keyring-pam",
    "gnulib-l10n",
    "gnupg2",
    "gnupg2-dirmngr",
    "gnupg2-gpg-agent",
    "gnupg2-gpgconf",
    "gnupg2-keyboxd",
    "gnupg2-verify",
    "gnutls",
    "gparted",
    "grep",
    "greybird-dark-theme",
    "greybird-light-theme",
    "greybird-xfce4-notifyd-theme",
    "greybird-xfwm4-theme",
    "grub2-pc",
    "gtk-xfce-engine",
    "gutenprint-cups",
    "gvfs-archive",
    "gvfs-mtp",
    "gzip",
    "hostname",
    "hplip",
    "ima-evm-utils-libs",
    "intel-audio-firmware",
    "intel-gpu-firmware",
    "intel-lpmd",
    "intel-vsc-firmware",
    "iproute",
    "iptables-nft",
    "iputils",
    "iwlegacy-firmware",
    "iwlwifi-dvm-firmware",
    "iwlwifi-mvm-firmware",
    "java-25-openjdk",
    "json-c",
    "kbd",
    "kbd-legacy",
    "kbd-misc",
    "keepassxc",
    "kernel",
    "kernel-core",
    "kernel-modules",
    "kernel-modules-core",
    "keyutils-libs",
    "kmod",
    "kmod-libs",
    "krb5-libs",
    "libacl",
    "libarchive",
    "libassuan",
    "libattr",
    "libblkid",
    "libbpf",
    "libbrotli",
    "libcap",
    "libcap-ng",
    "libcbor",
    "libcom_err",
    "libcurl",
    "libdnf5",
    "libdnf5-cli",
    "libdnf5-plugin-expired-pgp-keys",
    "libeconf",
    "libertas-firmware",
    "libevent",
    "libfdisk",
    "libffi",
    "libfido2",
    "libfsverity",
    "libgcc",
    "libgcrypt",
    "libgomp",
    "libgpg-error",
    "libidn2",
    "libksba",
    "libmodulemd",
    "libmount",
    "libnghttp2",
    "libnghttp3",
    "libpkgconf",
    "libpsl",
    "libpwquality",
    "librepo",
    "libseccomp",
    "libsecret",
    "libselinux",
    "libsepol",
    "libsmartcols",
    "libsolv",
    "libssh",
    "libssh-config",
    "libstdc++",
    "libtasn1",
    "libtool-ltdl",
    "libunistring",
    "libusb1",
    "libuuid",
    "libverto",
    "libxcrypt",
    "libxkbcommon",
    "libxml2",
    "libyaml",
    "libzstd",
    "lightdm-gtk",
    "lsb_release",
    "lua-libs",
    "lz4-libs",
    "mint-y-theme",
    "mkpasswd",
    "mpage",
    "mpdecimal",
    "mt7xxx-firmware",
    "ncurses",
    "ncurses-base",
    "ncurses-libs",
    "nettle",
    "NetworkManager",
    "network-manager-applet",
    "NetworkManager-bluetooth",
    "NetworkManager-fortisslvpn-gnome",
    "NetworkManager-iodine-gnome",
    "NetworkManager-l2tp-gnome",
    "NetworkManager-libreswan-gnome",
    "NetworkManager-openconnect-gnome",
    "NetworkManager-openvpn-gnome",
    "NetworkManager-ssh-gnome",
    "NetworkManager-sstp-gnome",
    "NetworkManager-strongswan-gnome",
    "NetworkManager-vpnc-gnome",
    "NetworkManager-wifi",
    "NetworkManager-wwan",
    "ngtcp2",
    "ngtcp2-crypto-ossl",
    "nm-connection-editor",
    "npth",
    "nvidia-gpu-firmware",
    "nxpwireless-firmware",
    "openldap",
    "openssh-askpass",
    "openssh-clients",
    "openssl-libs",
    "orpie",
    "p11-kit",
    "p11-kit-trust",
    "pam-libs",
    "paps",
    "parole",
    "pavucontrol",
    "pcre2",
    "pcre2-syntax",
    "pidgin",
    "pinentry",
    "pkcs11-provider",
    "pkgconf",
    "pkgconf-m4",
    "pkgconf-pkg-config",
    "policycoreutils",
    "popt",
    "pragha",
    "prefixdevname",
    "procps-ng",
    "publicsuffix-list-dafsa",
    "python3",
    "python3-ipython",
    "python3-libs",
    "python-pip-wheel",
    "python-unversioned-command",
    "qcom-wwan-firmware",
    "qrencode-libs",
    "qubes-artwork",
    "qubes-core-agent-thunar",
    "qubes-gui-agent-xfce",
    "qubes-kernel-vm-support",
    "readline",
    "realtek-firmware",
    "ristretto",
    "rootfiles",
    "rpm",
    "rpm-build-libs",
    "rpmfusion-free-release",
    "rpmfusion-nonfree-release",
    "rpm-libs",
    "rpm-plugin-audit",
    "rpm-sequoia",
    "rpm-sign-libs",
    "rxvt-unicode",
    "samba-client",
    "sdbus-cpp",
    "seahorse",
    "sed",
    "selinux-policy-targeted",
    "setup",
    "shadow-utils",
    "ShellCheck",
    "sqlite-libs",
    "sssd-common",
    "sssd-kcm",
    "system-config-printer-udev",
    "systemd",
    "systemd-libs",
    "systemd-networkd",
    "systemd-pam",
    "systemd-resolved",
    "systemd-shared",
    "systemd-sysusers",
    "systemd-udev",
    "Thunar",
    "tiwilink-firmware",
    "tpm2-tss",
    "transmission",
    "tumbler",
    "tzdata",
    "usb_modeswitch",
    "util-linux",
    "util-linux-core",
    "vim-enhanced",
    "vim-minimal",
    "wcurl",
    "wget2-wget",
    "whois-nls",
    "wpa_supplicant",
    "xdg-user-dirs-gtk",
    "xfburn",
    "xfce4-about",
    "xfce4-appfinder",
    "xfce4-clipman-plugin",
    "xfce4-datetime-plugin",
    "xfce4-dict-plugin",
    "xfce4-panel-profiles",
    "xfce4-places-plugin",
    "xfce4-power-manager",
    "xfce4-pulseaudio-plugin",
    "xfce4-screenshooter-plugin",
    "xfce4-session",
    "xfce4-settings",
    "xfce4-taskmanager",
    "xfdesktop",
    "xfwm4",
    "xfwm4-themes",
    "xkeyboard-config",
    "xz-libs",
    "zchunk-libs",
    "zlib-ng-compat",
    "zram-generator-defaults",
  ]
}

