arch = {
  packages = [
    "7zip",
    "aalib",
    "acme",
    "adw-gtk-theme",
    "adwaita-qt5-git",
    "adwaita-qt6-git",
    "aha",
    "alacritty",
    "android-sdk-build-tools",
    "android-sdk-platform-tools",
    "android-studio",
    "android-tools",
    "android-udev",
    "arch-wiki-docs",
    "asciiquarium",
    "aspell-en",
    "audacious",
    "audacious-plugins",
    "autoconf",
    "autoconf-archive",
    "automake",
    "balena-etcher",
    "bandwhich",
    "base",
    "base-devel",
    "binutils",
    "binutils-ia16",
    "bison",
    "bitwarden",
    "blueman",
    "bluez",
    "bluez-utils",
    "bpytop",
    "brave-bin",
    "btop",
    "bucklespring",
    "bzip2",
    "calibre",
    "cantata",
    "cc65",
    "ccache",
    "chaotic-keyring",
    "chaotic-mirrorlist",
    "chatbox-bin",
    "checksec",
    "cifs-utils",
    "clang",
    "clipmenu",
    "clisp",
    "cmake",
    "cmatrix",
    "cmus",
    "cndrvcups-lb-bin",
    "code",
    "cool-retro-term",
    "cowsay",
    "csvkit",
    "ctags",
    "cups",
    "curl",
    "dbeaver",
    "debtap",
    "debugedit",
    "deno",
    "dialog",
    "diffutils",
    "direnv",
    "discord",
    "djgpp-binutils",
    "djgpp-djcrx-bootstrap",
    "djgpp-gcc",
    "dmenu",
    "dos2unix",
    "dosbox",
    "dosfstools",
    "dotnet-runtime",
    "dotnet-sdk",
    "duf",
    "dysk",
    "easytag",
    "emacs",
    "eog",
    "ethtool",
    "evince",
    "exfatprogs",
    "expac",
    "fastfetch",
    "ffmpeg",
    "figlet",
    "firefox",
    "flex",
    "focuswriter",
    "font-manager",
    "fortunecraft",
    "fortune-mod-off",
    "fpc",
    "freebasic",
    "freetube",
    "fs-uae",
    "fs-uae-launcher",
    "fzf",
    "gajim",
    "gcc",
    "gcc-ia16",
    "genact",
    "gimp",
    "git",
    "github-desktop",
    "glibc",
    "gmp",
    "gnome-settings-daemon",
    "gnome-themes-extra",
    "gnuplot",
    "go",
    "gphoto2",
    "gradle",
    "gradle-doc",
    "graphviz",
    "grip",
    "gtk2",
    "gtk3",
    "gtk4",
    "guile",
    "gum",
    "gvfs",
    "gvfs-smb",
    "helvum",
    "hfsprogs",
    "htmlq",
    "htop",
    "hunspell-en_us",
    "id3lib",
    "id3v2",
    "iftop",
    "imagemagick",
    "inetutils",
    "inkscape",
    "intellij-idea-community-edition",
    "inxi",
    "iperf",
    "ipython",
    "irssi",
    "ispell",
    "jdk-openjdk",
    "jq",
    "jre",
    "keychain",
    "kicad",
    "kicad-library",
    "kitty",
    "kotlin",
    "languagetool",
    "lazarus",
    "lazarus-qt6",
    "lazygit",
    "lazyjournal",
    "ldns",
    "less",
    "lhasa",
    "libedit",
    "libreoffice-still",
    "libmpc",
    "links",
    "localsend",
    "lolcat",
    "lsb-release",
    "lsof",
    "lxappearance",
    "lynx",
    "m4",
    "mame",
    "man-db",
    "man-pages",
    "mc",
    "metapac",
    "moreutils",
    "mousepad",
    "mpc",
    "mpd",
    "mpdris2",
    "mpfr",
    "mplayer",
    "mpv",
    "mtools",
    "nano",
    "nasm",
    "netkit-bsd-finger",
    "net-tools",
    "nfs-utils",
    "ngspice",
    "nheko",
    "nmap",
    "nodejs-lts-jod",
    "noto-fonts",
    "noto-fonts-emoji",
    "ntfs-3g",
    "ocaml-csexp",
    "ollama",
    "ollama-docs",
    "openssl",
    "openwatcom-v2",
    "orpie",
    "pacman-contrib",
    "pamixer",
    "pandoc-bin",
    "papers",
    "paru",
    "patch",
    "perl-lwp-protocol-https",
    "perl-text-aspell",
    "picocom",
    "pingus",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "pipewire-qubes",
    "pkgfile",
    "plantuml",
    "plocate",
    "pup",
    "pysolfc",
    "python",
    "python-urllib3",
    "qmmp",
    "qt5ct",
    "qt5-tools",
    "qt6ct",
    "qt6-tools",
    "quassel-client",
    "qubes-vm-dependencies",
    "qubes-vm-recommended",
    "qubes-vm-repo",
    "qubes-vm-thunar",
    "quicklisp",
    "racket",
    "ranger",
    "remind",
    "ripgrep",
    "rofi",
    "rofimoji",
    "rpi-imager",
    "rsync",
    "ruby",
    "ruby-lsp",
    "rust",
    "rxvt-unicode",
    "samba",
    "sbcl",
    "screen",
    "scrot",
    "shellcheck",
    "shell-color-scripts-git",
    "sl",
    "slack-desktop",
    "smbclient",
    "speedtest-cli",
    "spotify",
    "stow",
    "sudo",
    "swift-bin",
    "system-config-printer",
    "terminology",
    "terminus-font",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-fontsrecommended",
    "texlive-latexextra",
    "texlive-pictures",
    "texlive-plaingeneric",
    "the_silver_searcher",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-vcs-plugin",
    "thunar-volman",
    "thunderbird",
    "tigervnc",
    "tldr",
    "tlp",
    "tmux",
    "tokei",
    "tor-browser-bin",
    "traceroute",
    "translate-shell",
    "transmission-gtk",
    "ttf-bitstream-vera",
    "ttf-dejavu",
    "ttf-inconsolata",
    "ttf-linux-libertine",
    "tty-clock",
    "tuba",
    "unifetch",
    "unipicker",
    "unison",
    "unzip",
    "usbutils",
    "vibrancy-colors",
    "vice",
    "vim",
    "vlc",
    "vlc-plugins-all",
    "vscodium",
    "w3m",
    "wget",
    "wine",
    "wine-gecko",
    "wine-mono",
    "winetricks",
    "wipe",
    "wireplumber",
    "woeusb",
    "wordgrinder",
    "x48ng",
    "xarchiver",
    "xclip",
    "xdg-utils",
    "xdo",
    "xdotool",
    "xfce4-terminal",
    "xgetres",
    "xorg-server",
    "xorg-xev",
    "xsel",
    "xterm",
    "yad",
    "ydotool",
    "yq",
    "yt-dlp",
    "zenity",
    "zip",
    "zlib",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "7zip",
    "aalib",
    "adw-gtk3-theme",
    "aha",
    "alacritty",
    "android-tools",
    "asciiquarium",
    "aspell-en",
    "audacious",
    "audacious-plugins",
    "autoconf",
    "autoconf-archive",
    "automake",
    "basiliskii",
    "binutils",
    "bison",
    "blueman",
    "bluez",
    "brave-origin",
    "btop",
    "bzip2",
    "calibre",
    "cantata",
    "cc65",
    "ccache",
    "checksec",
    "cifs-utils",
    "clang",
    "clipmenu",
    "clisp",
    "cmake",
    "cmatrix",
    "cool-retro-term",
    "cowsay",
    "ctags",
    "cups",
    "curl",
    "debugedit",
    "dialog",
    "diffutils",
    "direnv",
    "dmenu",
    "dos2unix",
    "dosbox",
    "dosfstools",
    "duf",
    "easytag",
    "emacs",
    "eog",
    "ethtool",
    "evince",
    "exfatprogs",
    "fastfetch",
    "ffmpeg",
    "figlet",
    "firefox",
    "flex",
    "focuswriter",
    "fortune-mod",
    "fpc",
    "fzf",
    "gajim",
    "gcc",
    "gimp",
    "git",
    "glibc",
    "gmp",
    "gnome-settings-daemon",
    "gnuplot",
    "golang",
    "gphoto2",
    "graphviz",
    "grip",
    "gtk2",
    "gtk3",
    "gtk4",
    "guile30",
    "gum",
    "gvfs",
    "gvfs-smb",
    "helvum",
    "htop",
    "id3lib",
    "id3v2",
    "iftop",
    "ImageMagick",
    "inkscape",
    "inxi",
    "iperf",
    "irssi",
    "ispell",
    "jq",
    "keychain",
    "kicad",
    "kicad-doc",
    "kitty",
    "lazarus",
    "ldns",
    "less",
    "lhasa",
    "libedit",
    "libreoffice",
    "libmpc",
    "links",
    "lolcat",
    "lsb-release",
    "lsof",
    "lxappearance",
    "lynx",
    "m4",
    "mame",
    "man-db",
    "man-pages",
    "mc",
    "metapac",
    "moreutils",
    "mousepad",
    "mpc",
    "mpd",
    "mpdris2",
    "mpfr",
    "mpv",
    "mtools",
    "nano",
    "nasm",
    "finger",
    "net-tools",
    "nfs-utils",
    "ngspice",
    "nheko",
    "nmap",
    "ntfs-3g",
    "ocaml-csexp",
    "ollama",
    "openssl",
    "pamixer",
    "pandoc-pdf",
    "papers",
    "patch",
    "perl-LWP-Protocol-https",
    "perl-Text-Aspell",
    "pingus",
    "pipewire",
    "pipewire-alsa",
    "pipewire-pulse",
    "pipewire-qubes",
    "plantuml",
    "plocate",
    "pysolfc",
    "python",
    "python-urllib3",
    "qmmp",
    "qt5ct",
    "qt6ct",
    "quassel-client",
    "qubes-vm-dependencies",
    "qubes-vm-recommended",
    "racket",
    "ranger",
    "remind",
    "ripgrep",
    "rofi",
    "rofimoji",
    "rpi-imager",
    "rsync",
    "ruby",
    "rust",
    "samba",
    "sbcl",
    "screen",
    "scrot",
    "shc",
    "shellcheck",
    "sl",
    "smbclient",
    "speedtest-cli",
    "stow",
    "sudo",
    "system-config-printer",
    "terminology",
    "the_silver_searcher",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-vcs-plugin",
    "thunar-volman",
    "thunderbird",
    "tigervnc",
    "tldr",
    "tlp",
    "tmux",
    "tokei",
    "torbrowser-launcher",
    "traceroute",
    "translate-shell",
    "transmission-gtk",
    "bitstream-vera-fonts-all",
    "dejavu-fonts-all",
    "google-noto-fonts-all",
    "levien-inconsolata-fonts",
    "linux-libertine-fonts-all",
    "tuba",
    "unison",
    "unzip",
    "usbutils",
    "vim",
    "vlc",
    "vlc-plugins-all",
    "w3m",
    "wget",
    "wine",
    "wine-mono",
    "winetricks",
    "wipe",
    "wireplumber",
    "wordgrinder",
    "xarchiver",
    "xclip",
    "xdg-utils",
    "xdotool",
    "xfce4-terminal",
    "xsel",
    "xterm",
    "yad",
    "ydotool",
    "yq",
    "yt-dlp",
    "zenity",
    "zip",
  ]
}

