arch = {
  packages = [
    "7zip",
    "acpi",
    "aha",
    "arch-wiki-docs",
    "aspell-en",
    "auto-cpufreq",
    "bandwhich",
    "bind",
    "bluez",
    "bluez-utils",
    "bpytop",
    "btop",
    "bzip2",
    "checksec",
    "cifs-utils",
    "cndrvcups-lb-bin",
    "cups",
    "debugedit",
    "direnv",
    "dos2unix",
    "dosfstools",
    "duf",
    "emacs",
    "ethtool",
    "exfatprogs",
    "expac",
    "fastfetch",
    "ffmpeg",
    "firewalld",
    "fwupd",
    "fzf",
    "gvfs",
    "gvfs-smb",
    "helvum",
    "hfsprogs",
    "htop",
    "hunspell-en_us",
    "hw-probe",
    "id3lib",
    "iftop",
    "imagemagick",
    "inxi",
    "iperf",
    "ispell",
    "jdk-openjdk",
    "keychain",
    "kitty",
    "languagetool",
    "ldns",
    "lhasa",
    "light",
    "lm_sensors",
    "lsb-release",
    "lshw",
    "moreutils",
    "mpc",
    "mpd",
    "mpdris2",
    "mtools",
    "net-tools",
    "netkit-bsd-finger",
    "nfs-utils",
    "nmap",
    "ntfs-3g",
    "ocaml-csexp",
    "orpie",
    "pamixer",
    "parted",
    "pass",
    "powertop",
    "psensor",
    "remind",
    "ripgrep",
    "samba",
    "screen",
    "smbclient",
    "system-config-printer",
    "the_silver_searcher",
    "tldr",
    "tmux",
    "traceroute",
    "unifetch",
    "unipicker",
    "veracrypt",
    "wipe",
    "woeusb",
    "ydotool",
    "zip",
    "unzip",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "7zip",
    "acpi",
    "aspell-en",
    "bluez",
    "btop",
    "bzip2",
    "checksec",
    "cifs-utils",
    "copr-rpmbuild",
    "cups",
    "debugedit",
    "direnv",
    "dos2unix",
    "dosfstools",
    "duf",
    "emacs",
    "ethtool",
    "exfatprogs",
    "fastfetch",
    "ffmpeg",
    "firewalld",
    "flatpak",
    "fwupd",
    "fzf",
    "htop",
    "hunspell-en-US",
    "hw-probe",
    "iftop",
    "ImageMagick",
    "inxi",
    "iperf",
    "java-latest-openjdk",
    "keychain",
    "kitty",
    "lhasa",
    "light",
    "lm_sensors",
    "lsb_release",
    "lshw",
    "moreutils",
    "mpc",
    "mpd",
    "mpdris2",
    "mtools",
    "net-tools",
    "finger",
    "nfs-utils",
    "nmap",
    "ntfs-3g",
    "parted",
    "powertop",
    "remind",
    "ripgrep",
    "samba",
    "screen",
    "snapd",
    "system-config-printer",
    "tar",
    "tcpdump",
    "the_silver_searcher",
    "thermald",
    "time",
    "tldr",
    "tmux",
    "traceroute",
    "ufiformat",
    "unipicker",
    "vim-enhanced",
    "vim-minimal",
    "which",
    "whois",
    "wipe",
    "words",
    "ydotool",
    "zip",
    "unzip",
    "gvfs",
    "gvfs-smb",
    "helvum",
    "id3lib",
    "wireplumber",
  ]
}

