arch = [
    "bandwhich",
    "barrier",
    "bluez",
    "bluez-utils",
    "cndrvcups-lb-bin",
    "cups",
    "davfs2",
    "dosfstools",
    "duf",
    "exfat-utils",
    "expac",
    "f3",
    "firewalld",
    "flatpak",
    "fwupd",
    "fzf",
    "gksu",
    "gnome-disk-utility",
    "gnome-keyring",
    "gvfs-smb",
    "hfsprogs",
    "hyperfine",
    "inxi",
    "lm_sensors",
    "iperf",
    "mtools",
    "neoss",
    "net-tools",
    "pass",
    "pamixer",
    "powertop",
    "psensor",
    "s-tui",
    "scrub",
    "shc",
    "smbclient",
    "smem",
    "sysbench",
    "sysz",
    "termite",
    "tig",
    "tlp",
    "traceroute",
    "ufiformat",
    "wipe",
    "w3m",
]