arch = {
  packages = [
    "7zip",
    "aha",
    "alacritty",
    "archlinux-keyring",
    "arch-wiki-docs",
    "aspell-en",
    "bandwhich",
    "base",
    "base-devel",
    "bluez",
    "bluez-utils",
    "bpytop",
    "btop",
    "bzip2",
    "chaotic-keyring",
    "chaotic-mirrorlist",
    "checksec",
    "cifs-utils",
    "cndrvcups-lb-bin",
    "coreutils",
    "cups",
    "curl",
    "debugedit",
    "direnv",
    "dos2unix",
    "dosfstools",
    "duf",
    "emacs",
    "ethtool",
    "exfatprogs",
    "expac",
    "fastfetch",
    "ffmpeg",
    "fzf",
    "git",
    "go",
    "gum",
    "gvfs",
    "gvfs-smb",
    "hfsprogs",
    "htop",
    "hunspell-en_us",
    "id3lib",
    "iftop",
    "imagemagick",
    "inetutils",
    "inxi",
    "iperf",
    "ispell",
    "jdk-openjdk",
    "keychain",
    "kitty",
    "languagetool",
    "ldns",
    "less",
    "lhasa",
    "lsb-release",
    "lsof",
    "man-db",
    "man-pages",
    "metapac",
    "moreutils",
    "mpc",
    "mpd",
    "mpdris2",
    "mtools",
    "nano",
    "netkit-bsd-finger",
    "net-tools",
    "networkmanager",
    "nfs-utils",
    "nmap",
    "ntfs-3g",
    "openssl",
    "orpie",
    "pacman-contrib",
    "pamixer",
    "paru",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "pkgfile",
    "plocate",
    "python",
    "remind",
    "ripgrep",
    "rpm-tools",
    "rsync",
    "rust",
    "rxvt-unicode",
    "samba",
    "screen",
    "smbclient",
    "stow",
    "sudo",
    "system-config-printer",
    "terminus-font",
    "the_silver_searcher",
    "tldr",
    "tlp",
    "tmux",
    "traceroute",
    "tree",
    "unifetch",
    "unipicker",
    "unixodbc",
    "unrar",
    "unzip",
    "usbutils",
    "vim",
    "vulkan-intel",
    "wget",
    "wipe",
    "wireplumber",
    "woeusb",
    "xdg-utils",
    "ydotool",
    "zip",
    "ocaml-csexp",
    "python-urllib3",
    "python-wxpython",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/nullman/packages",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "7zip",
    "alacritty",
    "aspell",
    "aspell-en",
    "attr",
    "bash",
    "bash-color-prompt",
    "bash-completion",
    "bind-utils",
    "bluez",
    "bluez-cups",
    "btop",
    "btrfs-progs",
    "bzip2",
    "checksec",
    "cifs-utils",
    "coreutils",
    "cryptsetup",
    "cups",
    "curl",
    "debugedit",
    "direnv",
    "dos2unix",
    "dosfstools",
    "duf",
    "emacs",
    "ethtool",
    "exfatprogs",
    "fastfetch",
    "ffmpeg",
    "file",
    "finger",
    "firewall-config",
    "firewalld",
    "flatpak",
    "flatseal",
    "fwupd",
    "fzf",
    "git",
    "gnupg2",
    "golang",
    "gum",
    "hostname",
    "htop",
    "hunspell",
    "hunspell-en-US",
    "hw-probe",
    "iftop",
    "ImageMagick",
    "inxi",
    "iperf",
    "iptstate",
    "java-latest-openjdk",
    "keychain",
    "kitty",
    "less",
    "lhasa",
    "light",
    "lm_sensors",
    "lsb_release",
    "lshw",
    "lsof",
    "mailcap",
    "man-db",
    "man-pages",
    "metapac",
    "moreutils",
    "mpc",
    "mpd",
    "mpdris2",
    "mtools",
    "nano",
    "net-tools",
    "NetworkManager",
    "nfs-utils",
    "nmap",
    "ntfs-3g",
    "nvme-cli",
    "openssh-clients",
    "openssh-server",
    "openssl",
    "orpie",
    "parted",
    "pipewire-alsa",
    "pipewire-config-raop",
    "pipewire-pulseaudio",
    "pipewire-utils",
    "plocate",
    "powertop",
    "python3",
    "remind",
    "ripgrep",
    "rsync",
    "rust",
    "samba",
    "samba-client",
    "sane-backends-drivers-scanners",
    "screen",
    "snapd",
    "speedtest",
    "stow",
    "strace",
    "sudo",
    "system-config-printer",
    "system-config-printer-udev",
    "tar",
    "tcpdump",
    "terminus-fonts",
    "thermald",
    "the_silver_searcher",
    "time",
    "tldr",
    "tlp",
    "tmux",
    "traceroute",
    "tree",
    "ufiformat",
    "unipicker",
    "unixodbc",
    "unzip",
    "usbutils",
    "vim-enhanced",
    "vim-minimal",
    "which",
    "whois",
    "wipe",
    "words",
    "ydotool",
    "zip",
    "acl",
    "cups-filters",
    "iproute",
    "quota",
    "gsl",
    "gvfs",
    "gvfs-smb",
    "helvum",
    "id3lib",
    "pciutils",
    "python-wxpython",
    "wireplumber",
  ]
}

