apt = [
    "atuin",
    "binsider",
    "bmon",
    "calcurse",
    "caligula",
    "cmus",
    "cointop",
    "dust",
    "elinks",
    "gomuks",
    "hexedit",
    "hexyl",
    "irssi",
    "links",
    "lynx",
    "mc",
    "mcabber",
    "ncdu",
    "ncmpcpp",
    "phetch",
    "ranger",
    "s-tui",
    "speedometer",
    "superfile",
    "tig",
    "ugrep",
    "visidata",
    "w3m",
    "wavemon",
    "wordgrinder",
    "x3270",
    "xplr",
    "yazi",
    "zenith-bin",
]

arch = [
    "atuin",
    "binsider",
    "bmon",
    "calcurse",
    "caligula",
    "cmus",
    "cointop",
    "dust",
    "elinks",
    "gomuks",
    "hexedit",
    "hexyl",
    "irssi",
    "links",
    "lynx",
    "mc",
    "mcabber",
    "ncdu",
    "ncmpcpp",
    "phetch",
    "ranger",
    "s-tui",
    "speedometer",
    "superfile",
    "tig",
    "ugrep",
    "visidata",
    "w3m",
    "wavemon",
    "wordgrinder",
    "x3270",
    "xplr",
    "yazi",
    "zenith-bin",
]

