arch = {
  packages = [
    "atuin",
    "binsider",
    "bmon",
    "calcurse",
    "caligula",
    "cmus",
    "elinks",
    "gomuks",
    "hexedit",
    "hexyl",
    "irssi",
    "links",
    "lynx",
    "mc",
    "mcabber",
    "ncdu",
    "ncmpcpp",
    "ranger",
    "s-tui",
    "superfile",
    "tig",
    "ugrep",
    "visidata",
    "w3m",
    "wordgrinder",
  ]
}

