arch = [
    "atuin",
    "binsider",
    "bmon",
    "calcurse",
    "caligula",
    "cmus",
    "cointop",
    "elinks",
    "gomuks",
    "hexedit",
    "hexyl",
    "irssi",
    "links",
    "lynx",
    "mc",
    "mcabber",
    "mop",
    "ncdu",
    "ncmpcpp",
    "phetch",
    "play",
    "qodem",
    "ranger",
    "rpncalc",
    "s-tui",
    "superfile",
    "tig",
    "tilde",
    "tty-clock",
    "tuifimanager",
    "ugrep",
    "w3m",
    "wavemon",
    "wordgrinder",
    "x3270",
    "xplr",
    "yazi",
    "zenith",
]