arch = [
    "bitwarden",
    "font-manager",
    "papers",
    "balena-etcher",
    "bat",
    "bitwarden-cli",
    "bitwarden-rofi",
    "broot",
    "calcurse",
    "cool-retro-term",
    "cpuburn",
    "daktilo",
    "devtoolbox",
    "exa",
    "fd",
    "file-roller",
    "flameshot",
    "frogmouth",
    "gcal",
    "gcalcli",
    "gdu",
    "glmark2",
    "googler",
    "gpart",
    "gparted",
    "hardinfo",
    "hdparm",
    "hexedit",
    "hexyl",
    "nodejs-how2",
    "hq",
    "intel-gpu-tools",
    "jq",
    "lsd",
    "meld",
    "mesa-utils",
    "miller",
    "mupdf-tools",
    "navi",
    "ncdu",
    "procs",
    "rar",
    "ripgrep",
    "sad",
    "sd",
    "sendmail",
    "sharutils",
    "sttr",
    "superfile-bin",
    "testdisk",
    "the_silver_searcher",
    "thefuck",
    "timidity++",
    "tokei",
    "ugrep",
    "units",
    "xarchiver",
    "xautolock",
    "xplr",
    "yq",
    "zenith-bin",
    "zoxide",
]