arch = [
    "asciinema",
    "asunder",
    "audacious",
    "balena-etcher",
    "bitwarden",
    "blanket",
    "brasero",
    "celluloid",
    "celluloid",
    "cherrytree",
    "cmus",
    "cool-retro-term",
    "czkawka",
    "deadbeef",
    "dmg2img",
    "easytag",
    "engrampa",
    "eog",
    "fim",
    "flameshot",
    "font-manager",
    "gcal",
    "geekbench",
    "gimp",
    "glmark2",
    "gnome-frog",
    "gnome-multi-writer",
    "gnuplot",
    "goldendict-ng",
    "gparted",
    "graphviz",
    "grip",
    "gtkimageview",
    "handbrake",
    "hpl",
    "id3lib",
    "isoimagewriter",
    "kdeconnect",
    "libaacs",
    "libation",
    "libbluray",
    "libdvdcss",
    "livecaptions",
    "makemkv",
    "mediawriter",
    "meld",
    "mission-center",
    "mplayer",
    "mplayer",
    "mpv",
    "mupdf-tools",
    "ncmpcpp",
    "notepadqq",
    "papers",
    "qmmp",
    "qmplay2",
    "rpi-imager",
    "scrcpy",
    "simplescreenrecorder",
    "sox",
    "sxiv",
    "timg",
    "virt-viewer",
    "vlc",
    "x48",
    "xpdf",
    "xarchiver",
    "ymuse",
    "zathura",
]