arch = {
  packages = [
    "adapta-gtk-theme",
    "adw-gtk-theme",
    "adwaita-qt5-git",
    "adwaita-qt6-git",
    "barrier",
    "barrier-headless",
    "blueman",
    "brightnessctl",
    "bspwm",
    "clipmenu",
    "conky",
    "dialog",
    "dmenu",
    "dunst",
    "eject-applet",
    "eog",
    "evtest",
    "eww",
    "gconf",
    "gksu",
    "gnome-disk-utility",
    "gnome-icon-theme",
    "gnome-icon-theme-extras",
    "gnome-icon-theme-symbolic",
    "gnome-keyring",
    "gnome-settings-daemon",
    "gnome-themes-extra",
    "gsimplecal",
    "gst-plugin-qml6",
    "gtk2",
    "gtk3",
    "gtk4",
    "gtk-engines",
    "gxmessage",
    "libgksu",
    "libglade",
    "libgnome-keyring",
    "lightdm",
    "lightdm-gtk-greeter",
    "localsend",
    "lxappearance",
    "menumaker",
    "mesa-demos",
    "mission-center",
    "ncpamixer",
    "network-manager-applet",
    "nitrogen",
    "pa-applet-git",
    "paprefs",
    "pasystray",
    "pavucontrol",
    "picom",
    "pinta",
    "playerctl",
    "polkit",
    "polybar",
    "qt5-tools",
    "qt6-tools",
    "qt5ct",
    "qt6ct",
    "rofi",
    "rofimoji",
    "seahorse",
    "stumpwm",
    "stumpwm-contrib",
    "sysstat",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-vcs-plugin",
    "thunar-volman",
    "tigervnc",
    "tint2",
    "tk",
    "tumbler",
    "unclutter",
    "unison",
    "vibrancy-colors",
    "wmctrl",
    "wmname",
    "xdg-desktop-portal-gnome",
    "xfce4-power-manager",
    "xfce4-terminal",
    "xfe",
    "xplanet",
    "xscreensaver",
    "xscreensaver-aerial",
    "yad",
    "zenity",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "adw-gtk3-theme",
    "barrier",
    "blueman",
    "brightnessctl",
    "bspwm",
    "clipmenu",
    "conky",
    "dialog",
    "dmenu",
    "dunst",
    "eog",
    "evtest",
    "gnome-disk-utility",
    "gnome-icon-theme",
    "gnome-keyring",
    "gnome-settings-daemon",
    "gtk2",
    "gtk3",
    "gtk4",
    "libgnome-keyring",
    "lxappearance",
    "mesa-demos",
    "nitrogen",
    "picom",
    "playerctl",
    "polkit",
    "polybar",
    "qt5ct",
    "qt6ct",
    "rofi",
    "rofimoji",
    "seahorse",
    "sysstat",
    "Thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-vcs-plugin",
    "thunar-volman",
    "tigervnc",
    "tk",
    "tumbler",
    "unclutter-xfixes",
    "wmctrl",
    "wmname",
    "xdg-desktop-portal-gnome",
    "xfce4-power-manager",
    "xfce4-terminal",
    "xfe",
    "xplanet",
    "xscreensaver",
    "xscreensaver-extras",
    "xscreensaver-gl-base",
    "xscreensaver-gl-extras",
    "yad",
    "zenity",
  ]
}

