arch = [
    "adapta-gtk-theme",
    "adw-gtk-theme",
    "adwaita-dark",
    "adwaita-qt5",
    "adwaita-qt6",
    "blueman",
    "bsp-layout",
    "bspwm",
    "clipmenu-rofi",
    "conky",
    "dialog",
    "dunst",
    "eject-applet",
    "eog",
    "evtest",
    "eww",
    "gksu",
    "gnome-disk-utility",
    "gnome-icon-theme",
    "gnome-icon-theme-extras",
    "gnome-keyring",
    "gnome-settings-daemon",
    "gsimplecal",
    "gxmessage",
    "kdeconnect",
    "keychain",
    "lightdm",
    "lightdm-gtk-greeter",
    "lxappearance",
    "menumaker",
    "mesa-demos",
    "mission-center",
    "ncpamixer",
    "network-manager-applet",
    "nitrogen",
    "paprefs",
    "pasystray",
    "pavucontrol",
    "picom",
    "playerctl",
    "polkit-gnome",
    "rofi",
    "rofimoji",
    "seahorse",
    "sysstat",
    "system-config-printer",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-vcs-plugin",
    "thunar-volman",
    "tint2",
    "tk",
    "unclutter",
    "vibrancy-colors",
    "webkit2gtk",
    "wmctrl",
    "wmname",
    "xfce4-power-manager",
    "xfe",
    "xfishtank",
    "xplanet",
    "xscreensaver",
    "xscreensaver-aerial",
    "yad",
    "zenity",
]