arch = [
    "adwaita-qt5",
    "adwaita-qt6",
    "tk",
    "unclutter",
    "dialog",
    "dunst",
    "gxmessage",
    "adapta-gtk-theme",
    "blueman",
    "bspwm",
    "clipit",
    "clipmenu-rofi",
    "cmus",
    "conky",
    "eject-applet",
    "evtest",
    "eww",
    "gnome-icon-theme",
    "gnome-icon-theme-extras",
    "gsimplecal",
    "lightdm",
    "lightdm-gtk-greeter",
    "lxappearance",
    "menumaker",
    "network-manager-applet",
    "nitrogen",
    "orage",
    "pa-applet-git",
    "paprefs",
    "pavucontrol",
    "pcmanfm-gtk3",
    "picom",
    "playerctl",
    "polkit-gnome",
    "rofi",
    "rofi-emoji",
    "rofimoji",
    "sysstat",
    "system-config-printer",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-vcs-plugin",
    "thunar-volman",
    "tint2",
    "vibrancy-colors",
    "webkit2gtk",
    "wmname",
    "yad",
    "zenity",
]