arch = [
    "arandr",
    "imwheel",
    "scrot",
    "sxhkd",
    "x2x-git",
    "xautolock",
    "xclip",
    "xdo",
    "xdotool",
    "xgetres",
    "xorg-server",
    "xorg-setxkbmap",
    "xorg-xbacklight",
    "xorg-xev",
    "xorg-xinit",
    "xorg-xinput",
    "xorg-xkbcomp",
    "xorg-xkill",
    "xorg-xmodmap",
    "xorg-xprop",
    "xorg-xrandr",
    "xorg-xset",
    "xorg-xwininfo",
    "xprintidle",
    "xsel",
    "xvkbd",
]