arch = [
    "arandr",
    "x2x-git",
    "xbindkeys",
    "xclip",
    "xdo",
    "xdotool",
    "xfe",
    "xgetres",
    "xorg-xbacklight",
    "xorg-xev",
    "xorg-xinit",
    "xorg-xinput",
    "xorg-xkill",
    "xorg-xprop",
    "xorg-xrandr",
    "xorg-xwininfo",
    "xorg-setxkbmap",
    "xorg-server",
    "xsel",
    "xvkbd",
]