arch = {
  packages = [
    "scrot",
    "xclip",
    "xdo",
    "xdotool",
    "xgetres",
    "xorg-server",
    "xorg-server-xephyr",
    "xorg-setxkbmap",
    "xorg-xev",
    "xorg-xrandr",
    "xsel",
    "xterm",
  ]
}

dnf = {
  repos = [
    "copr.fedorainfracloud.org/avengemedia/danklinux",
    "copr.fedorainfracloud.org/avengemedia/dms [eternal_deps]",
    "copr.fedorainfracloud.org/errornointernet/packages",
    "copr.fedorainfracloud.org/komapro/metapac",
    "copr.fedorainfracloud.org/nullman/packages",
    "copr.fedorainfracloud.org/rok/vdhcoapp",
    "copr.fedorainfracloud.org/skidnik/clipmenu",
  ], 
  packages = [
    "scrot",
    "xclip",
    "xdotool",
    "xorg-server",
    "xorg-server-xephyr",
    "xorg-setxkbmap",
    "xrandr",
    "xsel",
  ]
}

