apt = [
    "orage",
    "xfce4-appfinder",
    "xfce4-battery-plugin",
    "xfce4-clipman-plugin",
    "xfce4-cpufreq-plugin",
    "xfce4-cpugraph-plugin",
    "xfce4-datetime-plugin",
    "xfce4-dict",
    "xfce4-fsguard-plugin",
    "xfce4-genmon-plugin",
    "xfce4-mailwatch-plugin",
    "xfce4-mpc-plugin",
    "xfce4-netload-plugin",
    "xfce4-notes-plugin",
    "xfce4-notifyd",
    "xfce4-panel",
    "xfce4-pulseaudio-plugin",
    "xfce4-sensors-plugin",
    "xfce4-systemload-plugin",
    "xfce4-taskmanager",
    "xfce4-time-out-plugin",
    "xfce4-timer-plugin",
    "xfce4-volumed-pulse",
    "xfce4-weather-plugin",
    "xfce4-whiskermenu-plugin",
    "xfce4-windowck-plugin",
    "xfce4-xkb-plugin",
]

arch = [
    "orage",
    "xfce4-appfinder",
    "xfce4-battery-plugin",
    "xfce4-clipman-plugin",
    "xfce4-cpufreq-plugin",
    "xfce4-cpugraph-plugin",
    "xfce4-datetime-plugin",
    "xfce4-dict",
    "xfce4-fsguard-plugin",
    "xfce4-genmon-plugin",
    "xfce4-mailwatch-plugin",
    "xfce4-mpc-plugin",
    "xfce4-netload-plugin",
    "xfce4-notes-plugin",
    "xfce4-notifyd",
    "xfce4-panel",
    "xfce4-pulseaudio-plugin",
    "xfce4-sensors-plugin",
    "xfce4-systemload-plugin",
    "xfce4-taskmanager",
    "xfce4-time-out-plugin",
    "xfce4-timer-plugin",
    "xfce4-volumed-pulse",
    "xfce4-weather-plugin",
    "xfce4-whiskermenu-plugin",
    "xfce4-windowck-plugin",
    "xfce4-xkb-plugin",
]

