#!/usr/bin/env bash
# Battery Status
#
# Uses acpi to get the status of the battery.

[ -n "${BLOCK_INSTANCE}" ] && num=${BLOCK_INSTANCE} || num=0
desc=$(acpi -b | grep "Battery ${num}:" | grep -v "rate information unavailable")
[ -z "${desc}" ] && exit 0
status=$(echo "${desc}" | sed 's/^.*: \([^,]*\),.*$/\1/')
percent=$(echo "${desc}" | sed 's/^.*, \(.*\)%.*$/\1/')
remaining=$(echo "${desc}" | sed 's/^.*,.*, \(..:..\).*$/\1/')
color=""

#echo "Status: ${status}"
#echo "Percent: ${percent}"
#echo "Remaining: ${remaining}"

if [ "${status}" == "Discharging" ] ; then
    if [ ${percent} -lt 20 ] ; then
        text=""
        color="#FF0000"
    elif [ ${percent} -lt 40 ] ; then
        text=""
        color="#FFAE00"
    elif [ ${percent} -lt 60 ] ; then
        text=""
        color="#FFF600"
    elif [ ${percent} -lt 80 ] ; then
        text=""
        color="#A8FF00"
    else
        text=""
    fi
else
    text=""
fi

text="${text} ${percent}%"

if [ -n "$(echo ${remaining} | grep -v '^Battery')" ] ; then
    long="${text} (${remaining})"
else
    long="${text}"
fi

echo "${long}"
echo "${text}"
[ -n "${color}" ] && echo "${color}"

[ ${percent} -lt 5 ] && exit 33

exit 0
