[Appearance]
color_scheme_path=/home/user/.config/qt6ct/style-colors.conf
custom_palette=true
icon_theme=breeze-dark
standard_dialogs=gtk3
style=kvantum-dark

[Fonts]
fixed="MesloLGS Nerd Font Mono,12,-1,5,50,0,0,0,0,0,Regular"
general="MesloLGS Nerd Font,12,-1,5,50,0,0,0,0,0,Regular"
