[Appearance]
color_scheme_path=/home/user/.config/qt6ct/style-colors.conf
#color_scheme_path=/usr/share/qt6ct/colors/darker.conf
custom_palette=false
icon_theme=gnome
standard_dialogs=gtk3
#style=Adwaita-Dark
style=Breeze

[Fonts]
fixed="MesloLGS Nerd Font Mono,12,-1,5,50,0,0,0,0,0,Regular"
general="MesloLGS Nerd Font,12,-1,5,50,0,0,0,0,0,Regular"
