# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    "base-devel",
    "efibootmgr",
    "git",
    "grub",
    "linux-headers",
    "mdadm",
    "networkmanager",
    "os-prober",
    "stow",
    "terminus-font",
    "usbutils",
    "wireless_tools",
    "wpa_supplicant",
    "adwaita-qt5",
    "alacritty",
    "arandr",
    "aspell-en",
    "base",
    "base-devel",
    "bind",
    "btop",
    "debugedit",
    "dialog",
    "dunst",
    "emacs",
    "gxmessage",
    "htop",
    "iftop",
    "ipython",
    "ispell",
    "keychain",
    "languagetool",
    "lsb-release",
    "man-db",
    "man-pages",
    "nmap",
    "openssl",
    "pass",
    "pkgfile",
    "plocate",
    "python",
    "python-pip",
    "qt5-tools",
    "rsync",
    "screen",
    "scrot",
    "sxhkd",
    "tk",
    "tmux",
    "tmux-plugin-manager",
    "unclutter",
    "vim",
    "w3m",
    "bandwhich",
    "barrier",
    "bluez",
    "bluez-utils",
    "cndrvcups-lb-bin",
    "cups",
    "davfs2",
    "dosfstools",
    "duf",
    "exfat-utils",
    "expac",
    "f3",
    "firewalld",
    "flatpak",
    "fwupd",
    "fzf",
    "gnome-disk-utility",
    "gnome-keyring",
    "gvfs-smb",
    "hfsprogs",
    "hyperfine",
    "inxi",
    "lm_sensors",
    "iperf",
    "mtools",
    "neoss",
    "net-tools",
    "pamixer",
    "powertop",
    "psensor",
    "s-tui",
    "scrub",
    "shc",
    "smbclient",
    "smem",
    "sysbench",
    "sysz",
    "tig",
    "tlp",
    "traceroute",
    "ufiformat",
    "wipe",
    "xdg-user-dirs",
    "xdg-utils",
    "lightdm",
    "lightdm-slick-greeter",
    "webkit2gtk",
    "adapta-gtk-theme",
    "blueman",
    "clipmenu",
    "cmus",
    "conky",
    "eject-applet",
    "evtest",
    "gnome-icon-theme",
    "gnome-icon-theme-extras",
    "polkit-gnome",
    "gsimplecal",
    "lxappearance",
    "maia-gtk-theme",
    "menumaker",
    "network-manager-applet",
    "nitrogen",
    "orage",
    "pa-applet-git",
    "paprefs",
    "pavucontrol",
    "pcmanfm-gtk3",
    "picom",
    "playerctl",
    "rofi",
    "rofi-emoji",
    "rofimoji",
    "sysstat",
    "system-config-printer",
    "tint2",
    "vibrancy-colors",
    "x2x-git",
    "xbindkeys",
    "xclip",
    "xdg-utils",
    "xdo",
    "xdotool",
    "xfce4-power-manager",
    "xfce4-settings",
    "xfe",
    "xgetres",
    "xorg-xbacklight",
    "xorg-xev",
    "xorg-xinit",
    "xorg-xinput",
    "xorg-xkill",
    "xorg-xprop",
    "xorg-xrandr",
    "xorg-xwininfo",
    "xorg-setxkbmap",
    "xsel",
    "xvkbd",
    "yad",
    "zenity",
    "bspwm",
    "wmname",
    "adobe-source-han-fonts",
    "bdf-unifont",
    "cantarell-fonts",
    "gnu-free-fonts",
    "noto-fonts",
    "noto-fonts-emoji",
    "terminus-font",
    "ttf-anonymous-pro",
    "ttf-dejavu",
    "ttf-droid",
    "ttf-fira-code",
    "ttf-hack-nerd",
    "ttf-joypixels",
    "ttf-material-design-icons-webfont",
    "ttf-meslo-nerd",
    "ttf-mononoki",
    "ttf-ms-fonts",
    "ttf-terminus-nerd",
    "ttf-ubuntu-font-family",
    "xorg-fonts-100dpi",
    "xorg-fonts-75dpi",
    "xorg-fonts-misc",
    "xorg-fonts-type1",
    "xorg-xlsfonts",
    "antibody-bin",
    "ttf-meslo-nerd-font-powerlevel10k",
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "evince",
    "font-manager",
    "irssi",
    "libreoffice-fresh",
    "mc",
    "mop-git",
    "mpc",
    "mpd",
    "mpdris2",
    "nautilus",
    "neofetch",
    "notepadqq",
    "ranger",
    "remind",
    "xpdf",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-volman",
    "thunar-vcs-plugin",
    "fortune-mod",
    "xfishtank",
    "xplanet",
    "xscreensaver",
    "xscreensaver-aerial",
    "balena-etcher",
    "bat",
    "broot",
    "calcurse",
    "cpuburn",
    "daktilo",
    "devtoolbox",
    "exa",
    "fd",
    "file-roller",
    "flameshot",
    "frogmouth",
    "gcal",
    "gcalcli",
    "gdu",
    "glmark2",
    "googler",
    "gpart",
    "gparted",
    "hardinfo",
    "hexedit",
    "hexyl",
    "nodejs-how2",
    "hq",
    "jq",
    "lsd",
    "meld",
    "miller",
    "mupdf-tools",
    "navi",
    "ncdu",
    "procs",
    "rar",
    "ripgrep",
    "sad",
    "sd",
    "sendmail",
    "sharutils",
    "sttr",
    "testdisk",
    "the_silver_searcher",
    "thefuck",
    "timidity++",
    "tokei",
    "ugrep",
    "units",
    "xarchiver",
    "xautolock",
    "xplr",
    "yq",
    "zenith-bin",
    "zoxide",
    "bitwarden",
    "bitwarden-cli",
    "bitwarden-rofi",
    "betterbird-bin",
    "chromium",
    "ddgr",
    "elinks",
    "filezilla",
    "firefox",
    "flashplugin",
    "gnu-netcat",
    "gomuks",
    "gopherus",
    "hyperspace-bin",
    "inetutils",
    "kristall",
    "links",
    "lynx",
    "mcabber",
    "minicom",
    "mtr",
    "nyxt",
    "pepper-flash",
    "phetch",
    "surf",
    "surfraw",
    "syncterm",
    "vdhcoapp-bin",
    "binutils",
    "ccache",
    "cmake",
    "cool-retro-term",
    "github-desktop",
    "gradle",
    "gradle-doc",
    "jdk-openjdk",
    "jdk11-openjdk",
    "jdk17-openjdk",
    "jdk8-openjdk",
    "ruby",
    "rustup",
    "asciinema",
    "eog",
    "fim",
    "gimp",
    "gnuplot",
    "graphviz",
    "mplayer",
    "sxiv",
    "timg",
    "audacious",
    "cmus",
    "deadbeef",
    "ncmpcpp",
    "qmmp",
    "sox",
    "celluloid",
    "mplayer",
    "vlc",
    "dosbox",
    "wine",
    "wine-gecko",
    "wine-mono",
    "winetricks",
    "aalib",
    "asciiquarium",
    "bullshit",
    "cbonsai-git",
    "cmatrix",
    "cowsay",
    "figlet",
    "fortune-mod",
    "genact",
    "hacker-typer",
    "hollywood",
    "lolcat",
    "rig",
    "sl",

]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
