# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    "acpi",
    "auto-cpufreq",
    "bind",
    "efibootmgr",
    "firewalld",
    "fwupd",
    "gst-plugin-pipewire",
    "hw-probe",
    "intel-media-driver",
    "intel-ucode",
    "iwd",
    "libpulse",
    "libva-intel-driver",
    "light",
    "linux",
    "linux-firmware",
    "linux-headers",
    "lm_sensors",
    "lshw",
    "mkinitcpio",
    "os-prober",
    "parted",
    "powertop",
    "psensor",
    "smartmontools",
    "wireless_tools",
    "wpa_supplicant",
    "********* Base-WM (Window Manager)",
    "#+NAME: arch-packages",
    "Package Name",
    "arandr",
    "barrier",
    "barrier-headless",
    "brightnessctl",
    "bspwm",
    "conky",
    "dunst",
    "eject-applet",
    "evtest",
    "eww",
    "gnome-disk-utility",
    "gxmessage",
    "imwheel",
    "lightdm",
    "lightdm-gtk-greeter",
    "menumaker",
    "mission-center",
    "ncpamixer",
    "network-manager-applet",
    "nitrogen",
    "numlockx",
    "pa-applet-git",
    "paprefs",
    "pasystray",
    "pavucontrol",
    "picom",
    "polybar",
    "stumpwm",
    "stumpwm-contrib",
    "sxhkd",
    "sysstat",
    "tint2",
    "unclutter",
    "wmctrl",
    "wmname",
    "x2x-git",
    "xautolock",
    "xdg-desktop-portal-gnome",
    "xfce4-power-manager",
    "xorg-xbacklight",
    "xorg-xinit",
    "xorg-xinput",
    "xorg-xkbcomp",
    "xorg-xkill",
    "xorg-xmodmap",
    "xorg-xprop",
    "xorg-xset",
    "xorg-xwininfo",
    "xplanet",
    "xprintidle",
    "xscreensaver",
    "xscreensaver-aerial",
    "libglade",
    "********* System",
    "#+NAME: arch-packages",
    "Package Name",
    "7zip",
    "aha",
    "alacritty",
    "archlinux-keyring",
    "arch-wiki-docs",
    "aspell-en",
    "bandwhich",
    "base",
    "base-devel",
    "bluez",
    "bluez-utils",
    "bpytop",
    "btop",
    "bzip2",
    "chaotic-keyring",
    "chaotic-mirrorlist",
    "checksec",
    "cifs-utils",
    "cndrvcups-lb-bin",
    "coreutils",
    "cups",
    "curl",
    "debugedit",
    "direnv",
    "dos2unix",
    "dosfstools",
    "dovecot",
    "duf",
    "emacs",
    "ethtool",
    "exfatprogs",
    "expac",
    "fastfetch",
    "ffmpeg",
    "fzf",
    "git",
    "go",
    "gum",
    "gvfs",
    "gvfs-smb",
    "hfsprogs",
    "htop",
    "hunspell-en_us",
    "id3lib",
    "iftop",
    "imagemagick",
    "inetutils",
    "inxi",
    "iperf",
    "ispell",
    "jdk-openjdk",
    "keychain",
    "kitty",
    "languagetool",
    "ldns",
    "less",
    "lhasa",
    "lsb-release",
    "lsof",
    "man-db",
    "man-pages",
    "metapac",
    "moreutils",
    "mpc",
    "mpd",
    "mpdris2",
    "mtools",
    "nano",
    "netkit-bsd-finger",
    "net-tools",
    "networkmanager",
    "nfs-utils",
    "nmap",
    "ntfs-3g",
    "openssl",
    "orpie",
    "pacman-contrib",
    "pamixer",
    "paru",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "pkgfile",
    "plocate",
    "pv",
    "python",
    "remind",
    "ripgrep",
    "rpm-tools",
    "rsync",
    "rust",
    "rxvt-unicode",
    "samba",
    "screen",
    "smbclient",
    "stow",
    "sudo",
    "system-config-printer",
    "terminus-font",
    "the_silver_searcher",
    "tldr",
    "tlp",
    "tmux",
    "traceroute",
    "tree",
    "unifetch",
    "unipicker",
    "unixodbc",
    "unrar",
    "unzip",
    "usbutils",
    "vim",
    "vulkan-intel",
    "wget",
    "wipe",
    "wireplumber",
    "woeusb",
    "xdg-utils",
    "ydotool",
    "zip",
    "ocaml-csexp",
    "python-urllib3",
    "python-wxpython",
    "********* X11",
    "#+NAME: arch-packages",
    "Package Name",
    "espanso-x11-git",
    "scrot",
    "xclip",
    "xdo",
    "xdotool",
    "xf86-video-intel",
    "xgetres",
    "xorg-server",
    "xorg-server-xephyr",
    "xorg-setxkbmap",
    "xorg-xev",
    "xorg-xrandr",
    "xsel",
    "xterm",
    "********* Wayland",
    "#+NAME: arch-packages",
    "Package Name",
    "clipman",
    "espanso-wayland-git",
    "foot",
    "fuzzel",
    "grim",
    "hyprland",
    "hyprpaper",
    "hyprpicker",
    "mako",
    "niri",
    "slurp",
    "sway",
    "swaybg",
    "swayidle",
    "swaylock",
    "waybar",
    "wayland",
    "wayland-protocols",
    "wayland-utils",
    "wmenu",
    "wpaperd",
    "wtype",
    "wl-clipboard",
    "wl-color-picker",
    "wlroots0.19",
    "wofi",
    "xorg-xwayland",
    "********* WM (Window Manager)",
    "#+NAME: arch-packages",
    "Package Name",
    "adapta-gtk-theme",
    "adwaita-qt5-git",
    "adwaita-qt6-git",
    "adw-gtk-theme",
    "blueman",
    "breeze",
    "breeze5",
    "breeze-gtk",
    "clipmenu",
    "dialog",
    "dmenu",
    "eog",
    "gnome-icon-theme",
    "gnome-icon-theme-symbolic",
    "gnome-keyring",
    "gnome-settings-daemon",
    "gnome-themes-extra",
    "gsimplecal",
    "gst-plugin-qml6",
    "gtk2",
    "gtk3",
    "gtk4",
    "localsend",
    "lxappearance",
    "mesa-demos",
    "pinta",
    "playerctl",
    "polkit",
    "qt5ct",
    "qt5-tools",
    "qt6ct",
    "qt6-tools",
    "rofi",
    "rofimoji",
    "seahorse",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-vcs-plugin",
    "thunar-volman",
    "tigervnc",
    "tumbler",
    "xfce4-terminal",
    "xvkbd",
    "yad",
    "zenity",
    "********* Fonts",
    "#+NAME: arch-packages",
    "Package Name",
    "noto-fonts",
    "noto-fonts-emoji",
    "ttf-bitstream-vera",
    "ttf-dejavu",
    "ttf-inconsolata",
    "ttf-linux-libertine",
    "ttf-meslo-nerd",
    "ttf-nerd-fonts-symbols",
    "ttf-nerd-fonts-symbols-common",
    "********* XFCE",
    "#+NAME: arch-packages",
    "Package Name",
    "exo",
    "garcon",
    "mousepad",
    "parole",
    "ristretto",
    "xfburn",
    "xfce4-artwork",
    "xfce4-diskperf-plugin",
    "xfce4-eyes-plugin",
    "xfce4-mount-plugin",
    "xfce4-places-plugin",
    "xfce4-screensaver",
    "xfce4-screenshooter",
    "xfce4-session",
    "xfce4-settings",
    "xfce4-smartbookmark-plugin",
    "xfce4-verve-plugin",
    "xfce4-wavelan-plugin",
    "xfconf",
    "xfdesktop",
    "xfwm4",
    "xfwm4-themes",
    "********* XFCE Panel",
    "#+NAME: arch-packages",
    "Package Name",
    "orage",
    "xfce4-appfinder",
    "xfce4-battery-plugin",
    "xfce4-clipman-plugin",
    "xfce4-cpufreq-plugin",
    "xfce4-cpugraph-plugin",
    "xfce4-datetime-plugin",
    "xfce4-dict",
    "xfce4-fsguard-plugin",
    "xfce4-genmon-plugin",
    "xfce4-mailwatch-plugin",
    "xfce4-mpc-plugin",
    "xfce4-netload-plugin",
    "xfce4-notes-plugin",
    "xfce4-notifyd",
    "xfce4-panel",
    "xfce4-pulseaudio-plugin",
    "xfce4-sensors-plugin",
    "xfce4-systemload-plugin",
    "xfce4-taskmanager",
    "xfce4-time-out-plugin",
    "xfce4-timer-plugin",
    "xfce4-volumed-pulse",
    "xfce4-weather-plugin",
    "xfce4-whiskermenu-plugin",
    "xfce4-windowck-plugin",
    "xfce4-xkb-plugin",
    "********* Applications",
    "#+NAME: arch-packages",
    "Package Name",
    "ardour",
    "audacity",
    "calibre",
    "cantata",
    "drawing",
    "electrum",
    "evince",
    "focuswriter",
    "foliate",
    "freetube",
    "furnace",
    "gimp",
    "inkscape",
    "libreoffice-still",
    "ngspice",
    "shortwave",
    "spotify",
    "gst-plugins-bad",
    "kicad-library",
    "zbar",
    "********* Utilities",
    "#+NAME: arch-packages",
    "Package Name",
    "audacious",
    "audacious-plugins",
    "balena-etcher",
    "bitwarden",
    "blanket",
    "brasero",
    "celluloid",
    "cool-retro-term",
    "drawy",
    "easyeffects",
    "easytag",
    "engrampa",
    "flameshot",
    "font-manager",
    "galendae-git",
    "gnome-multi-writer",
    "gparted",
    "gphoto2",
    "grip",
    "handbrake",
    "isoimagewriter",
    "libaacs",
    "libbluray",
    "libdvdcss",
    "meld",
    "mplayer",
    "mpv",
    "mupdf-tools",
    "papers",
    "qmmp",
    "rpi-imager",
    "scrcpy",
    "sox",
    "sxiv",
    "unison",
    "vlc",
    "vlc-plugins-all",
    "x48ng",
    "nodejs-lts-jod",
    "********* Internet",
    "#+NAME: arch-packages",
    "Package Name",
    "brave-origin-bin",
    "copyparty",
    "dino",
    "discord",
    "element-desktop",
    "filezilla",
    "firefox",
    "gajim",
    "magic-wormhole",
    "nheko",
    "nyxt",
    "opensnitch",
    "quassel-client",
    "quassel-core",
    "slack-desktop",
    "surfraw",
    "syncterm-git",
    "telegram-desktop",
    "thunderbird",
    "tor-browser-bin",
    "transmission-gtk",
    "tuba",
    "********* TUI (Text-Based User Interface)",
    "#+NAME: arch-packages",
    "Package Name",
    "atuin",
    "binsider",
    "bmon",
    "calcurse",
    "caligula",
    "cmus",
    "elinks",
    "gomuks",
    "hexedit",
    "hexyl",
    "irssi",
    "links",
    "lynx",
    "mc",
    "mcabber",
    "ncdu",
    "ncmpcpp",
    "ranger",
    "s-tui",
    "superfile",
    "tig",
    "ugrep",
    "visidata",
    "w3m",
    "wordgrinder",
    "********* Console",
    "#+NAME: arch-packages",
    "Package Name",
    "asciinema",
    "bat",
    "bc",
    "broot",
    "chezmoi",
    "daktilo",
    "ddgr",
    "diskonaut",
    "dysk",
    "element",
    "fd",
    "file-roller",
    "gdu",
    "glmark2",
    "gpart",
    "gping",
    "hardinfo2",
    "hdparm",
    "hyperfine",
    "id3v2",
    "intel-gpu-tools",
    "lsd",
    "mesa-utils",
    "miller",
    "minicom",
    "mtr",
    "navi",
    "perl-image-exiftool",
    "picocom",
    "procs",
    "sad",
    "sd",
    "sharutils",
    "speedtest-cli",
    "stress",
    "sysbench",
    "testdisk",
    "timidity++",
    "translate-shell",
    "yt-dlp",
    "********* Console Hacks",
    "#+NAME: arch-packages",
    "Package Name",
    "aalib",
    "asciiquarium",
    "bucklespring",
    "cmatrix",
    "cowsay",
    "figlet",
    "genact",
    "lolcat",
    "shell-color-scripts-git",
    "sl",
    "tty-clock",
    "********* Emulators",
    "#+NAME: arch-packages",
    "Package Name",
    "dosbox",
    "fs-uae",
    "fs-uae-launcher",
    "mame",
    "vice",
    "wine",
    "wine-gecko",
    "wine-mono",
    "winetricks",
    "********* Virtual",
    "#+NAME: arch-packages",
    "Package Name",
    "edk2-ovmf",
    "guestfs-tools",
    "libosinfo",
    "qemu-base",
    "qemu-desktop",
    "qemu-emulators-full",
    "qemu-img",
    "swtpm",
    "virt-install",
    "virt-manager",
    "virt-viewer",
    "virtualbox",
    "libguestfs",
    "yara",
    "********* Containers",
    "#+NAME: arch-packages",
    "Package Name",
    "distrobox",
    "docker",
    "docker-compose",
    "podman",
    "********* Development",
    "#+NAME: arch-packages",
    "Package Name",
    "acme",
    "android-sdk-build-tools",
    "android-sdk-platform-tools",
    "android-studio",
    "android-tools",
    "android-udev",
    "autoconf",
    "autoconf-archive",
    "automake",
    "binutils",
    "binutils-ia16",
    "bison",
    "cc65",
    "ccache",
    "clang",
    "clisp",
    "cmake",
    "code",
    "csvkit",
    "ctags",
    "dbeaver",
    "debtap",
    "deno",
    "diffutils",
    "djgpp-binutils",
    "djgpp-djcrx-bootstrap",
    "djgpp-gcc",
    "dotnet-runtime",
    "dotnet-sdk",
    "flex",
    "fpc",
    "freebasic",
    "gcc",
    "gcc-ia16",
    "github-desktop",
    "glibc",
    "gmp",
    "gnuplot",
    "gradle",
    "gradle-doc",
    "graphviz",
    "guile",
    "htmlq",
    "intellij-idea-community-edition",
    "ipython",
    "jq",
    "jre",
    "kotlin",
    "lazarus",
    "lazarus-qt6",
    "lazygit",
    "lazyjournal",
    "libedit",
    "libmpc",
    "m4",
    "mpfr",
    "nasm",
    "openwatcom-v2",
    "pandoc-bin",
    "patch",
    "perl-lwp-protocol-https",
    "perl-text-aspell",
    "plantuml",
    "pup",
    "quicklisp",
    "racket",
    "ruby",
    "ruby-lsp",
    "sbcl",
    "shellcheck",
    "swift-bin",
    "terminology",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-fontsrecommended",
    "texlive-latexextra",
    "texlive-plaingeneric",
    "texlive-pictures",
    "tokei",
    "vscodium",
    "yq",
    "zlib",
    "********* AI (Artificial Intelligence)",
    "#+NAME: arch-packages",
    "Package Name",
    "chatbox-bin",
    "ollama",
    "ollama-docs",
    "fortunecraft",
    "********* Zsh",
    "#+NAME: arch-packages",
    "Package Name",
    "antibody-bin",
    "autojump",
    "ttf-meslo-nerd-font-powerlevel10k",
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "zsh-theme-powerlevel10k",
    "********* Fortune",
    "#+NAME: arch-packages",
    "Package Name",
    "fortune-mod-off",
    "********* Games",
    "#+NAME: arch-packages",
    "Package Name",
    "0ad",
    "dwarffortress",
    "luanti",
    "lutris",
    "mangohud",
    "pingus",
    "pysolfc",
    "rocksndiamonds",
    "steam",
    "supertux",
    "supertuxkart",
    "umu-launcher",
    "wesnoth",
    "0ad-data",
    "libxmp",
    "pysolfc-cardsets",
    "python-attrs",
    "python-configobj",
    "python-pygame",
    "python-pysol_cards",
    "sdl2_image",
    "sdl2_mixer",
    "sdl_mixer",
    "********* Nvidia",
    "#+NAME: arch-packages",
    "Package Name",
    "cuda",
    "egl-gbm",
    "lact",
    "lib32-nvidia-utils",
    "nvidia",
    "nvidia-settings",
    "nvidia-utils",
    "ollama-cuda",
    "********* Nvidia 470",
    "#+NAME: arch-packages",
    "Package Name",
    "egl-gbm",
    "lact",
    "lib32-nvidia-470xx-utils",
    "nvidia-470xx-dkms",
    "nvidia-470xx-settings",
    "nvidia-470xx-utils",
    "nvidia-prime",
    "opencl-nvidia-470xx",
    "********* Nvidia 580",
    "#+NAME: arch-packages",
    "Package Name",
    "cuda12.0",
    "egl-gbm",
    "lact",
    "lib32-nvidia-580xx-utils",
    "nvidia-580xx-dkms",
    "nvidia-580xx-settings",
    "nvidia-580xx-utils",
    "nvidia-prime",
    "ollama-cuda12-bin",
    "opencl-nvidia-580xx",
    "********* Minimal",
    "#+NAME: arch-packages",
    "Package Name",
    "audacious",
    "audacious-plugins",
    "brave-bin",
    "cmus",
    "cool-retro-term",
    "cowsay",
    "figlet",
    "font-manager",
    "gnuplot",
    "graphviz",
    "lazygit",
    "lazyjournal",
    "links",
    "lynx",
    "mc",
    "mplayer",
    "mpv",
    "papers",
    "plantuml",
    "ranger",
    "speedtest-cli",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-latexextra",
    "texlive-pictures",
    "translate-shell",
    "vlc",
    "w3m",
    "wordgrinder",
    "x48ng",
    "zlib",
    "********* Qubes",
    "#+NAME: arch-packages",
    "Package Name",
    "pipewire-qubes",
    "qubes-db-vm",
    "qubes-gpg-split",
    "qubes-img-converter",
    "qubes-pdf-converter",
    "qubes-usb-proxy",
    "qubes-vm-core",
    "qubes-vm-dependencies",
    "qubes-vm-gui",
    "qubes-vm-kernel-support",
    "qubes-vm-networking",
    "qubes-vm-passwordless-root",
    "qubes-vm-recommended",
    "qubes-vm-repo",
    "qubes-vm-utils",

]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
