# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    "alacritty",
    "base",
    "base-devel",
    "chaotic-keyring",
    "chaotic-mirrorlist",
    "coreutils",
    "curl",
    "efibootmgr",
    "git",
    "gst-plugin-pipewire",
    "inetutils",
    "intel-media-driver",
    "intel-ucode",
    "iwd",
    "libpulse",
    "libva-intel-driver",
    "linux",
    "linux-firmware",
    "linux-headers",
    "metapac",
    "nano",
    "networkmanager",
    "openssl",
    "os-prober",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "pkgfile",
    "plocate",
    "python",
    "python-pip",
    "reflector",
    "rsync",
    "rxvt-unicode",
    "smartmontools",
    "stow",
    "sudo",
    "terminus-font",
    "usbutils",
    "vim",
    "vulkan-intel",
    "wget",
    "wireless_tools",
    "wireplumber",
    "xdg-utils",
    "yay",
    "7zip",
    "acpi",
    "aha",
    "arch-wiki-docs",
    "aspell-en",
    "auto-cpufreq",
    "bandwhich",
    "barrier",
    "barrier-headless",
    "bluez",
    "bluez-utils",
    "bpytop",
    "brightnessctl",
    "btop",
    "bzip2",
    "cifs-utils",
    "cndrvcups-lb-bin",
    "coolercontrol-bin",
    "cups",
    "debugedit",
    "direnv",
    "dos2unix",
    "dosfstools",
    "duf",
    "emacs",
    "exfat-utils",
    "expac",
    "fastfetch",
    "firewalld",
    "flatpak",
    "fwupd",
    "fzf",
    "gvfs-smb",
    "helvum",
    "hfsprogs",
    "htop",
    "id3lib",
    "iftop",
    "imagemagick",
    "inxi",
    "iperf",
    "ispell",
    "keychain",
    "kitty",
    "languagetool",
    "lhasa",
    "light",
    "lm_sensors",
    "lsb-release",
    "lshw",
    "lsof",
    "man-db",
    "man-pages",
    "micro",
    "moreutils",
    "mpc",
    "mpd",
    "mpdris2",
    "mtools",
    "multitail",
    "neofetch",
    "neoss",
    "net-tools",
    "netkit-bsd-finger",
    "nfs-utils",
    "nitch",
    "nmap",
    "ntfs-3g",
    "orpie",
    "pamixer",
    "parted",
    "pass",
    "powertop",
    "psensor",
    "remind",
    "ripgrep",
    "samba",
    "screen",
    "scrub",
    "shc",
    "smbclient",
    "system-config-printer",
    "sysz",
    "termite",
    "the_silver_searcher",
    "tldr",
    "tlp",
    "tmux",
    "tmux-plugin-manager",
    "traceroute",
    "trash-cli",
    "ufiformat",
    "unipicker",
    "unison",
    "veracrypt",
    "vtop",
    "wipe",
    "woeusb",
    "ydotool",
    "zip",
    "arandr",
    "imwheel",
    "numlockx",
    "scrot",
    "sxhkd",
    "x2x-git",
    "xautolock",
    "xclip",
    "xdo",
    "xdotool",
    "xgetres",
    "xlibre-xserver",
    "xorg-server-xephyr",
    "xorg-setxkbmap",
    "xorg-xbacklight",
    "xorg-xev",
    "xorg-xinit",
    "xorg-xinput",
    "xorg-xkbcomp",
    "xorg-xkill",
    "xorg-xmodmap",
    "xorg-xprop",
    "xorg-xrandr",
    "xorg-xset",
    "xorg-xwininfo",
    "xprintidle",
    "xsel",
    "xterm",
    "xvkbd",
    "clipman",
    "hyprland",
    "hyprpaper",
    "hyprpicker",
    "rofi-wayland",
    "swww",
    "waybar",
    "wayland",
    "wayland-protocols",
    "wayland-utils",
    "wl-clipboard",
    "wl-color-picker",
    "wlroots0.19",
    "wofi",
    "xorg-xwayland",
    "adapta-gtk-theme",
    "adw-gtk-theme",
    "adwaita-dark",
    "adwaita-qt5",
    "adwaita-qt6",
    "blueman",
    "bsp-layout",
    "bspwm",
    "clipmenu-rofi",
    "conky",
    "dialog",
    "dmenu",
    "dunst",
    "eject-applet",
    "eog",
    "evtest",
    "eww",
    "gconf",
    "gksu",
    "gnome-disk-utility",
    "gnome-icon-theme",
    "gnome-icon-theme-extras",
    "gnome-icon-theme-symbolic",
    "gnome-keyring",
    "gnome-settings-daemon",
    "gnome-themes-extra",
    "gsimplecal",
    "gst-plugin-qml6",
    "gxmessage",
    "lightdm",
    "lightdm-gtk-greeter",
    "localsend-bin",
    "lxappearance",
    "menumaker",
    "mesa-demos",
    "mission-center",
    "ncpamixer",
    "network-manager-applet",
    "nitrogen",
    "pa-applet-git",
    "paprefs",
    "pasystray",
    "pavucontrol",
    "picom",
    "pinta",
    "playerctl",
    "polkit-gnome",
    "qt5ct",
    "qt6ct",
    "rofi",
    "rofimoji",
    "seahorse",
    "stumpwm",
    "stumpwm-contrib",
    "sysstat",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-vcs-plugin",
    "thunar-volman",
    "tint2",
    "tk",
    "tumbler",
    "unclutter",
    "vibrancy-colors",
    "webkit2gtk",
    "wmctrl",
    "wmname",
    "xfce4-power-manager",
    "xfce4-terminal",
    "xfe",
    "xplanet",
    "xscreensaver",
    "xscreensaver-aerial",
    "yad",
    "zenity",
    "xfburn",
    "xfce4-artwork",
    "xfce4-diskperf-plugin",
    "xfce4-eyes-plugin",
    "xfce4-mount-plugin",
    "xfce4-places-plugin",
    "xfce4-screensaver",
    "xfce4-screenshooter",
    "xfce4-session",
    "xfce4-settings",
    "xfce4-smartbookmark-plugin",
    "xfce4-verve-plugin",
    "xfce4-wavelan-plugin",
    "xfconf",
    "xfdesktop",
    "xfwm4",
    "xfwm4-themes",
    "orage",
    "xfce4-appfinder",
    "xfce4-battery-plugin",
    "xfce4-clipman-plugin",
    "xfce4-cpufreq-plugin",
    "xfce4-cpugraph-plugin",
    "xfce4-datetime-plugin",
    "xfce4-dict",
    "xfce4-fsguard-plugin",
    "xfce4-genmon-plugin",
    "xfce4-mailwatch-plugin",
    "xfce4-mpc-plugin",
    "xfce4-netload-plugin",
    "xfce4-notes-plugin",
    "xfce4-notifyd",
    "xfce4-panel",
    "xfce4-pulseaudio-plugin",
    "xfce4-sensors-plugin",
    "xfce4-systemload-plugin",
    "xfce4-taskmanager",
    "xfce4-time-out-plugin",
    "xfce4-timer-plugin",
    "xfce4-volumed-pulse",
    "xfce4-weather-plugin",
    "xfce4-whiskermenu-plugin",
    "xfce4-windowck-plugin",
    "xfce4-xkb-plugin",
    "ardour",
    "audacity",
    "blender",
    "calibre",
    "cantata",
    "drawing",
    "electrum",
    "focuswriter",
    "foliate",
    "freecad",
    "freemind-bin",
    "freetube-bin",
    "fritzing",
    "furnace",
    "gimp",
    "inkscape",
    "kdenlive",
    "kicad",
    "kicad-library",
    "kiwix-desktop",
    "kiwix-tools",
    "libreoffice-still",
    "lmms",
    "logisim-evolution-bin",
    "ngspice",
    "obs-studio",
    "openscad",
    "reaper",
    "shortwave",
    "spotify",
    "asunder",
    "audacious",
    "balena-etcher",
    "bitwarden",
    "blanket",
    "brasero",
    "celluloid",
    "cherrytree",
    "cool-retro-term",
    "czkawka-gui",
    "deadbeef",
    "dmg2img",
    "easytag",
    "engrampa",
    "fim",
    "flameshot",
    "font-manager",
    "gnome-multi-writer",
    "gparted",
    "gphoto2",
    "gtkimageview",
    "handbrake",
    "isoimagewriter",
    "libaacs",
    "libation",
    "libbluray",
    "libdvdcss",
    "livecaptions",
    "makemkv",
    "mediawriter",
    "meld",
    "mplayer",
    "mpv",
    "mupdf-tools",
    "papers",
    "qmmp",
    "qmplay2",
    "rpi-imager",
    "scrcpy",
    "sox",
    "sxiv",
    "timg",
    "ventoy-bin",
    "virt-viewer",
    "vlc",
    "vlc-plugins-all",
    "x48ng",
    "xpdf",
    "xarchiver",
    "ymuse-bin",
    "zathura",
    "atuin",
    "binsider",
    "bmon",
    "calcurse",
    "caligula",
    "cmus",
    "cointop",
    "elinks",
    "gomuks",
    "hexedit",
    "hexyl",
    "irssi",
    "links",
    "lynx",
    "mc",
    "mcabber",
    "ncdu",
    "ncmpcpp",
    "phetch",
    "ranger",
    "s-tui",
    "speedometer",
    "superfile",
    "tig",
    "ugrep",
    "visidata",
    "w3m",
    "wavemon",
    "wordgrinder",
    "xplr",
    "yazi",
    "zenith-bin",
    "alpine",
    "argc",
    "asciinema",
    "bat",
    "bc",
    "boxes",
    "broot",
    "chezmoi",
    "cp437",
    "cpuburn",
    "daktilo",
    "ddgr",
    "devtoolbox",
    "dict",
    "diskonaut",
    "element",
    "eza",
    "f3",
    "fd",
    "file-roller",
    "frogmouth",
    "gcalcli",
    "gdu",
    "geekbench",
    "glmark2",
    "googler",
    "gpart",
    "gping",
    "hardinfo2",
    "hdparm",
    "hyperfine",
    "id3v2",
    "intel-gpu-tools",
    "lsd",
    "mesa-utils",
    "miller",
    "minicom",
    "mtr",
    "navi",
    "nodejs-how2",
    "phoronix-test-suite",
    "procs",
    "rar",
    "sad",
    "sd",
    "sendmail",
    "sharutils",
    "smem",
    "speedtest-cli",
    "stress",
    "sttr-bin",
    "sysbench",
    "testdisk",
    "textual-paint",
    "thefuck",
    "timidity++",
    "translate-shell",
    "units",
    "yt-dlp",
    "zoxide",
    "aalib",
    "asciiquarium",
    "bb",
    "bullshit",
    "cbonsai",
    "cmatrix",
    "cowsay",
    "figlet",
    "genact",
    "hacker-typer",
    "hollywood",
    "lolcat",
    "no-more-secrets",
    "rig",
    "shell-color-scripts-git",
    "sl",
    "tty-clock",
    "betterbird-bin",
    "brave-bin",
    "bruno-bin",
    "carburetor",
    "copyparty",
    "dino",
    "discord",
    "element-desktop",
    "filezilla",
    "firefox",
    "flashplugin",
    "gajim",
    "gnu-netcat",
    "gopherus",
    "gossip-bin",
    "hyperspace-bin",
    "kristall",
    "magic-wormhole",
    "nheko",
    "nyxt",
    "opensnitch",
    "pepper-flash",
    "pidgin",
    "quassel-client",
    "searxng-git",
    "simplex-chat-bin",
    "slack-desktop",
    "surf",
    "surfraw",
    "syncterm-git",
    "telegram-desktop",
    "thunderbird-bin",
    "tor-browser-bin",
    "tractor",
    "transmission-gtk",
    "tribler-bin",
    "tuba",
    "vdhcoapp",
    "waterfox-bin",
    "basiliskii-git",
    "dosbox",
    "fs-uae",
    "fs-uae-launcher",
    "linapple-git",
    "mame",
    "minivmac",
    "vice",
    "wine",
    "wine-gecko",
    "wine-mono",
    "winetricks",
    "acme",
    "android-sdk-build-tools",
    "android-sdk-platform-tools",
    "android-studio",
    "android-tools",
    "android-udev",
    "autoconf",
    "autoconf-archive",
    "automake",
    "better-adb-sync-git",
    "binutils",
    "binutils-ia16",
    "bison",
    "bucklespring",
    "cc65",
    "ccache",
    "chibi-scheme",
    "cht.sh-git",
    "clang",
    "clisp",
    "cmake",
    "code",
    "csvkit",
    "ctags",
    "dbeaver",
    "debtap",
    "deno",
    "diffutils",
    "djgpp-binutils",
    "djgpp-djcrx-bootstrap",
    "djgpp-gcc",
    "dotnet-runtime",
    "dotnet-sdk",
    "flex",
    "fpc",
    "freebasic",
    "gcc",
    "gcc-ia16",
    "glibc",
    "gmp",
    "gnuplot",
    "go",
    "gpp",
    "gradle",
    "gradle-doc",
    "graphviz",
    "guile",
    "hq",
    "htmlq",
    "intellij-idea-community-edition",
    "ipython",
    "jdk-openjdk",
    "jq",
    "jqp",
    "jre",
    "kotlin",
    "lazarus",
    "lazarus-qt6",
    "lazygit",
    "lazyjournal",
    "libedit",
    "libmpc",
    "m4",
    "mpfr",
    "multimarkdown",
    "nasm",
    "openwatcom-v2",
    "pandoc-bin",
    "patch",
    "perl-lwp-protocol-https",
    "perl-text-aspell",
    "plantuml",
    "pup",
    "qt5-tools",
    "qt6-tools",
    "racket",
    "regina-rexx",
    "regina-rexx-doc",
    "ruby",
    "ruby-lsp",
    "rust",
    "sbcl",
    "shellcheck",
    "swift-bin",
    "tass64",
    "terminology",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-fontsrecommended",
    "texlive-latexextra",
    "texlive-pictures",
    "tokei",
    "vasm",
    "vlang",
    "vlink",
    "x16-docs-bin",
    "x16-emulator-bin",
    "x16-rom-bin",
    "yq",
    "zlib",
    "distrobox",
    "docker",
    "docker-compose",
    "podman",
    "chatbox-bin",
    "imaginer",
    "lmstudio",
    "ollama",
    "ollama-docs",
    "fortunecraft",
    "upscayl-bin",
    "antibody-bin",
    "autojump",
    "ttf-meslo-nerd-font-powerlevel10k",
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "zsh-theme-powerlevel10k",
    "fortune-mod-archlinux",
    "fortune-mod-asoiaf",
    "fortune-mod-bofh-excuses",
    "fortune-mod-confucius",
    "fortune-mod-farscape",
    "fortune-mod-firefly",
    "fortune-mod-futurama",
    "fortune-mod-hackers",
    "fortune-mod-hitchhiker",
    "fortune-mod-montypython",
    "fortune-mod-off",
    "fortune-mod-starwars",
    "fortune-mod-xfiles",
    "0ad",
    "celeste64-bin",
    "dwarffortress",
    "frozen-bubble",
    "luanti",
    "lutris",
    "osu-lazer-bin",
    "pingus",
    "pysolfc",
    "rocksndiamonds",
    "steam",
    "supertux",
    "supertuxkart",
    "tuxracer",
    "unciv-bin",
    "wesnoth",
    "xgalaga++",
    "xonotic",
    "cuda",
    "lib32-nvidia-utils",
    "nvidia",
    "nvidia-utils",
    "xf86-video-intel",
    "cuda",
    "lib32-nvidia-470xx-utils",
    "nvidia-470xx-dkms",
    "nvidia-470xx-utils",
    "nvidia-prime",
    "opencl-nvidia-470xx",
    "xf86-video-intel",
    "pipewire-qubes",
    "qubes-vm-dependencies",
    "qubes-vm-recommended",
    "qubes-vm-repo",
    "acme",
    "audacious",
    "autoconf",
    "autoconf-archive",
    "automake",
    "binutils",
    "binutils-ia16",
    "bison",
    "bitwarden",
    "blanket",
    "brave-bin",
    "bucklespring",
    "cc65",
    "ccache",
    "chibi-scheme",
    "cht.sh-git",
    "clang",
    "clisp",
    "cmake",
    "cool-retro-term",
    "csvkit",
    "ctags",
    "diffutils",
    "djgpp-binutils",
    "djgpp-djcrx-bootstrap",
    "djgpp-gcc",
    "freebasic",
    "gcc",
    "gcc-ia16",
    "glibc",
    "gmp",
    "gnuplot",
    "go",
    "gparted",
    "gpp",
    "graphviz",
    "guile",
    "hq",
    "htmlq",
    "ipython",
    "jq",
    "jqp",
    "lazygit",
    "lazyjournal",
    "libedit",
    "libmpc",
    "m4",
    "meld",
    "mpfr",
    "mplayer",
    "mpv",
    "nasm",
    "openwatcom-v2",
    "pandoc-bin",
    "papers",
    "patch",
    "plantuml",
    "racket",
    "regina-rexx",
    "regina-rexx-doc",
    "ruby",
    "ruby-lsp",
    "sbcl",
    "tass64",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-latexextra",
    "texlive-pictures",
    "translate-shell",
    "vasm",
    "vlang",
    "vlc",
    "x16-docs-bin",
    "x16-emulator-bin",
    "x16-rom-bin",
    "x48ng",
    "ymuse-bin",
    "yq",
    "zlib",

]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
