dnf = {
  packages = [
    "7zip",
    "aalib",
    "adw-gtk3-theme",
    "aha",
    "alacritty",
    "android-tools",
    "asciiquarium",
    "aspell-en",
    "audacious",
    "audacious-plugins",
    "autoconf",
    "autoconf-archive",
    "automake",
    "binutils",
    "bison",
    "blueman",
    "bluez",
    "btop",
    "bzip2",
    "calibre",
    "cantata",
    "cc65",
    "ccache",
    "checksec",
    "cifs-utils",
    "clang",
    "clipmenu",
    "clisp",
    "cmake",
    "cmatrix",
    "cool-retro-term",
    "cowsay",
    "ctags",
    "cups",
    "curl",
    "debugedit",
    "dialog",
    "diffutils",
    "direnv",
    "dmenu",
    "dos2unix",
    "dosbox",
    "dosfstools",
    "duf",
    "easytag",
    "emacs",
    "eog",
    "ethtool",
    "evince",
    "exfatprogs",
    "fastfetch",
    "ffmpeg",
    "figlet",
    "firefox",
    "flex",
    "focuswriter",
    "fpc",
    "fzf",
    "gajim",
    "gcc",
    "gimp",
    "git",
    "glibc",
    "gmp",
    "gnome-settings-daemon",
    "gnuplot",
    "go",
    "gphoto2",
    "graphviz",
    "grip",
    "gtk2",
    "gtk3",
    "gtk4",
    "guile",
    "gum",
    "gvfs",
    "gvfs-smb",
    "helvum",
    "htop",
    "id3lib",
    "id3v2",
    "iftop",
    "ImageMagick",
    "inkscape",
    "inxi",
    "iperf",
    "ipython",
    "irssi",
    "ispell",
    "jq",
    "jre",
    "keychain",
    "kicad",
    "kitty",
    "lazarus",
    "ldns",
    "less",
    "lhasa",
    "libedit",
    "libmpc",
    "links",
    "lolcat",
    "lsb-release",
    "lsof",
    "lxappearance",
    "lynx",
    "m4",
    "mame",
    "man-db",
    "man-pages",
    "mc",
    "metapac",
    "moreutils",
    "mousepad",
    "mpc",
    "mpd",
    "mpdris2",
    "mpfr",
    "mpv",
    "mtools",
    "nano",
    "nasm",
    "net-tools",
    "nfs-utils",
    "ngspice",
    "nheko",
    "nmap",
    "ntfs-3g",
    "ocaml-csexp",
    "ollama",
    "openssl",
    "pamixer",
    "papers",
    "patch",
    "perl-LWP-Protocol-https",
    "perl-Text-Aspell",
    "pingus",
    "pipewire",
    "pipewire-alsa",
    "pipewire-pulse",
    "pipewire-qubes",
    "plantuml",
    "plocate",
    "pysolfc",
    "python",
    "python-urllib3",
    "qmmp",
    "qt5ct",
    "qt6ct",
    "quassel-client",
    "qubes-vm-dependencies",
    "qubes-vm-recommended",
    "racket",
    "ranger",
    "remind",
    "ripgrep",
    "rofi",
    "rofimoji",
    "rpi-imager",
    "rsync",
    "ruby",
    "rust",
    "rxvt-unicode",
    "samba",
    "sbcl",
    "screen",
    "scrot",
    "shc",
    "shellcheck",
    "sl",
    "smbclient",
    "speedtest-cli",
    "stow",
    "sudo",
    "system-config-printer",
    "terminology",
    "the_silver_searcher",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-vcs-plugin",
    "thunar-volman",
    "thunderbird",
    "tigervnc",
    "tldr",
    "tlp",
    "tmux",
    "tokei",
    "traceroute",
    "translate-shell",
    "transmission-gtk",
    "tuba",
    "unison",
    "unzip",
    "usbutils",
    "vim",
    "vlc",
    "vlc-plugins-all",
    "w3m",
    "wget",
    "wine",
    "wine-mono",
    "winetricks",
    "wipe",
    "wireplumber",
    "wordgrinder",
    "xarchiver",
    "xclip",
    "xdg-utils",
    "xdotool",
    "xfce4-terminal",
    "xsel",
    "xterm",
    "yad",
    "ydotool",
    "yq",
    "yt-dlp",
    "zenity",
    "zip",
    "zlib",

  ]
}


