#!/usr/bin/env bash
#===============================================================================
# .config/bspwm/bspwmrc
#
# Binary Space Partitioning Window Manager (bspwm) configuration.
#
# Reference: https://github.com/baskerville/bspwm
# Reference: https://gitlab.com/protesilaos/dotfiles/-/blob/v2.2.0/bspwm/.config/bspwm/bspwmrc
#===============================================================================

# check if executable command is found in the path
_command() {
    command -v "$1" >/dev/null 2>&1
}

# bspc config
_bc() {
    bspc config "$@"
}

# bspc rule --add
_br() {
    bspc rule --add "$@"
}

#-------------------------------------------------------------------------------
# Configuration
#-------------------------------------------------------------------------------

# general settings
_bc split_ratio                0.5
#_bc stacked_layout             true
_bc stacked_direction          east
_bc stacked_ratio              0.7
_bc automatic_scheme           alternate
#_bc initial_polarity           first_child
_bc initial_polarity           second_child
_bc removal_adjustment         true
_bc borderless_monocle         false
_bc gapless_monocle            false
_bc single_monocle             true
_bc click_to_focus             any
_bc swallow_first_click        false
_bc focus_follows_pointer      false
_bc pointer_follows_monitor    true
_bc ignore_ewmh_focus          true
#_bc ignore_ewmh_focus          false
_bc ignore_ewmh_fullscreen     none
_bc ignore_ewmh_struts         false
_bc center_pseudo_tiled        true
_bc honor_size_hints           true
_bc remove_disabled_monitors   true
_bc remove_unplugged_monitors  true
_bc merge_overlapping_monitors true

# monitor and desktop settings
_bc top_padding                0
_bc right_padding              0
#_bc bottom_padding             0
#_bc bottom_padding             30       # room for tint2 system bar
_bc bottom_padding             22       # room for xfce/eww system bar
_bc left_padding               0

# desktop settings
_bc window_gap                 4

# node settings
_bc border_width               4

# pointer bindings
_bc pointer_modifier           mod1
_bc pointer_action1            resize_side
_bc pointer_action1            resize_corner
_bc pointer_action3            move

# default colors
#_bc normal_border_color        "#30302F"
#_bc active_border_color        "#474645"
#_bc focused_border_color       "#817F7F"
#_bc presel_feedback_color      "#F4D775"

# custom colors
_bc normal_border_color        "#4C566A"
_bc active_border_color        "#1E1E1E"
_bc focused_border_color       "#5E81AC"
_bc presel_feedback_color      "#5E81AC"

#-------------------------------------------------------------------------------
# Monitors
#-------------------------------------------------------------------------------

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12
#bspc monitor -d "1  " "2  " "3  " "4  " "5  " "6  " "7  " "8  " "9  " "10  "
#bspc monitor -d "1  " "2  " "3  " "4  " "5  " "6  " "7  " "8  " "9  " "10  "

#-------------------------------------------------------------------------------
# Application Desktop Assignments
#-------------------------------------------------------------------------------

# 1: Terminal
#bspc desktop 1 --layout stacked
#_br 'Alacritty' desktop=^1 follow=on

# 2: Editor
#bspc desktop 2 --layout stacked
_br 'Emacs' desktop=^2 follow=on

# 3: Email
bspc desktop 3 --layout monocle
_br 'thunderbird' desktop=^3 follow=on
_br 'betterbird' desktop=^3 follow=on
_br 'ms-outlook-nativefier' desktop=^3 follow=on

# 4: Browser
bspc desktop 4 --layout monocle
_br 'Brave-browser' desktop=^4 follow=on
_br 'vivaldi-stable' desktop=^4 follow=on
_br 'gopherus-sdl' desktop=^4 follow=on

# 5: File Manager
bspc desktop 5 --layout monocle
_br 'Thunar' desktop=^5 follow=on
_br 'Pcmanfm' desktop=^5 follow=on
_br 'Spacefm' desktop=^5 follow=on
_br 'Org.gnome.Nautilus' desktop=^5 follow=on

# 6: Chat
#bspc desktop 6 --layout tiled
_br 'quassel' desktop=^6 follow=on
_br 'Slack' desktop=^6 follow=on
_br 'discord' desktop=^6 follow=on

# 7: More Chat
#bspc desktop 7 --layout stacked
_br 'Pidgin' desktop=^7 follow=on
_br 'Tootle' desktop=^7 follow=on
_br 'Com.github.bleakgrey.tootle' desktop=^7 follow=on
_br 'nheko' desktop=^7 follow=on
_br 'Element' desktop=^7 follow=on
_br 'dev.geopjr.Tuba' desktop=^7 follow=on
_br 'Gajim' desktop=^7 follow=on
_br 'Hyperspace Desktop' desktop=^7 follow=on
_br 'android-messages-desktop' desktop=^7 follow=on
_br 'teams-for-linux' desktop=^7 follow=on

# 8: Development/Games
bspc desktop 8 --layout monocle
_br 'jetbrains-idea' desktop=^8 follow=on
_br 'jetbrains-idea-ce' desktop=^8 follow=on
_br 'jetbrains-studio' desktop=^8 follow=on
#_br 'dosbox' desktop=^8 follow=on
#_br 'BasiliskII' desktop=^8 follow=on
#_br 'syncterm' desktop=^8 follow=on
_br 'VirtualBox Manager' desktop=^8 follow=on
_br 'VirtualBox Machine' desktop=^8 follow=on

# 9: Image, Video, and Audio
bspc desktop 9 --layout monocle
_br 'firefox' desktop=^9 follow=on
_br 'Firefox' desktop=^9 follow=on
_br 'firefox-esr' desktop=^9 follow=on
_br 'LibreWolf' desktop=^9 follow=on
_br 'Chromium-browser' desktop=^9 follow=on
_br 'Google-chrome' desktop=^9 follow=on
_br 'Gimp-2.10' desktop=^9 follow=on
_br 'Qmmp' desktop=^9 follow=on
_br 'mplayer2' desktop=^9 follow=on
_br 'Lollypop' desktop=^9 follow=on
_br 'spotify' desktop=^9 follow=on

# 10: Administration/General
#bspc desktop 10 --layout monocle

# 11: Virtual Machine 1
bspc desktop 11 --layout monocle
_br 'windows-7' desktop=^11 follow=on

# 12: Virtual Machine 2
bspc desktop 12 --layout monocle

#-------------------------------------------------------------------------------
# Application Rules
#-------------------------------------------------------------------------------

# tiled applications
_br 'Emacs' state=tiled

# fullscreen applications
_br 'bluejeans-v2' state=fullscreen
_br 'Evince' state=fullscreen
_br 'Ghb' state=fullscreen
_br 'Gimp-2.10' state=fullscreen
_br 'haiku' state=fullscreen
#_br 'jetbrains-idea' state=fullscreen
#_br 'jetbrains-idea-ce' state=fullscreen
#_br 'jetbrains-studio' state=fullscreen
#_br 'Microsoft Teams' state=fullscreen
_br 'mplayer2' state=fullscreen
_br 'Papers' state=fullscreen
#_br 'spotify' state=fullscreen
_br 'vlc' state=fullscreen
_br 'VirtualBox Manager' state=fullscreen
_br 'VirtualBox Machine' state=fullscreen
_br 'w40k.exe' state=fullscreen
_br 'windows-xp' state=fullscreen
_br 'windows-7' state=fullscreen
_br 'windows-10' state=fullscreen
_br 'windows-11' state=fullscreen

# floating applications
_br 'About Pale Moon' state=floating center=true
_br 'alsamixer' state=floating center=true
_br 'arandr' state=floating center=true
_br 'Audacious' state=floating sticky=true center=false
_br 'balena-etcher-electron' state=floating center=true
_br 'BasiliskII' state=floating center=true
_br '.blueman-manager-wrapped' state=floating center=true
_br 'Calamares' state=floating center=true
_br 'Clipgrab' state=floating center=true
#_br 'dosbox' state=floating center=true
_br 'feh' state=floating center=true
_br 'File Transfer*' state=floating center=true
_br 'Font-manager' state=floating center=true
_br 'Font-viewer' state=floating center=true
_br 'Galculator' state=floating center=true
_br 'Gnome-disks' state=floating center=true
_br 'GParted' state=floating center=true
_br 'Gxmessage' state=floating center=true
_br 'gsimplecal' state=floating center=true
_br 'iwgtk' state=floating center=true
#_br 'jetbrains-idea' state=floating center=true
#_br 'jetbrains-idea-ce' state=floating center=true
#_br 'jetbrains-studio' state=floating center=true
_br 'Lightdm-gtk-greeter-settings' state=floating center=true
_br 'Lxappearance' state=floating center=true
_br 'Manjaro-hello' state=floating center=true
_br 'Manjaro Settings Manager' state=floating center=true
_br 'mpv' state=floating center=true sticky=on
_br 'MuseScore: Play Panel' state=floating center=true sticky=on
_br 'Nitrogen' state=floating center=true
_br 'oblogout' state=floating center=true
_br 'octopi' state=floating center=true
_br 'Pamac-manager' state=floating center=true
_br 'Paprefs' state=floating center=true
_br 'Pavucontrol' state=floating center=true
_br 'Qube Manager' state=floating center=true
_br 'Qube Settings' state=floating center=true
_br 'Qubes-app-menu' state=floating rectangle=640x480+0-20
_br 'Qubes-global-config' state=floating center=true
_br 'qubes-qube-manager' state=floating center=true
_br 'Qubes-update-gui' state=floating center=true
_br 'Qmmp' state=floating sticky=true
_br 'qt5ct' state=floating sticky=true
_br 'Qtconfig-qt4' state=floating sticky=true
_br 'Rofi' state=floating center=true
_br 'Simple-scan' state=floating center=true
_br 'System-config-printer.py' state=floating center=true
_br 'Skype' state=floating center=true
_br 'Thus' state=floating center=true
_br 'Tint2conf' state=floating center=true
_br 'Timeset-gui' state=floating center=true
_br 'virtualbox' state=floating center=true
_br 'X48' state=floating center=true
_br 'Xfburn' state=floating center=true
_br 'Xfce4-panel' state=floating center=true
_br 'Xfce4-settings-manager' state=floating center=true
_br 'Xfsettingsd' state=floating center=true
_br 'Xscreensaver-settings' state=floating center=true
_br 'Yad' state=floating center=true
_br 'zenity' state=floating center=true
_br 'Zenity' state=floating center=true

#-------------------------------------------------------------------------------
# Auto-Start Standard Applications
#-------------------------------------------------------------------------------

# # https://wiki.archlinux.org/title/bspwm#Problems_with_Java_applications
# # set window manager name so that java applications work
# wmname LG3D
# # fix java app not refreshing issue in tiling window managers
# export _JAVA_AWT_WM_NONREPARENTING=1

# check if executable command is found in the path
_command() {
    command -v "$1" >/dev/null 2>&1
}

# # delay running a command (SECONDS COMMAND)
# _delay() {
#     local delay=$1
#     shift
#     sleep ${delay} && eval "$@"
# }

# simple x hotkey daemon
# (might have been started already by .xprofile)
[[ -f "${HOME}/bin/run-sxhkd" ]] && ${HOME}/bin/run-sxhkd &

# qubes os
if [[ "$(uname -n)" == "dom0" ]] ; then
    # qubes volume block device attach home partition to personal
    (for device in $(qvm-block list --all | grep -e 'Unknown device' -e 'personal' | sed 's/ .*$//') ; do
         qvm-block detach personal ${device}
     done
     qvm-block attach --persistent --option frontend-dev=xvdz personal $(qvm-block list dom0 | grep 'dom0' | sed 's/ .*$//')) &

    # qubes usb device attach bluetooth to personal
    (for device in $(qvm-usb list --all | grep -e 'Unknown device' -e 'personal' | sed 's/ .*$//') ; do
         qvm-usb detach personal ${device}
     done
     qvm-usb attach --persistent personal $(qvm-usb list sys-net | grep '8087:0aaa' | sed 's/ .*$//')) &

    # xfce session
    _command xfce4-session && xfce4-session &

    # # system bar
    # _command xfce4-panel && xfce4-panel &

    # hide mouse when not in use
    _command unclutter && unclutter &

    # custom bspwm external rules to handle vm classes
    bspc config external_rules_command ${HOME}/.config/bspwm/bspwm-external-rules &
fi

# other os
if [[ "$(uname -n)" != "dom0" ]] ; then
    # xfce settings
    #_command xfsettingsd && xfsettingsd &

    # ssh-agent
    #_command ssh-agent && ssh-agent &
    #_command ssh-add && ssh-add &

    # key bindings
    #xmodmap "${HOME}/.xmodmaprc" &
    #set-xkb &
    #xbindkeys &

    # policykit authentation agent
    #if [[ -x /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 ]] ; then
    #    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
    #    #eval "$(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)" &
    #fi
    #_command lxpolkit && lxpolkit &

    # compositor
    _command picom && picom -b &

    # system bar
    [[ -f "${HOME}/bin/system-bar" ]] && source "${HOME}/bin/system-bar"

    # system wallpaper displays
    [[ -f "${HOME}/bin/system-wallpaper-displays" ]] && source "${HOME}/bin/system-wallpaper-displays"

    # full-screen task-switcher
    #_command skippy-xd && skippy-xd --config "${HOME}/.config/skippy-xd/skippy-xd.rc" --start-daemon &

    # localize user system folders
    #_command xdg-user-dirs-gtk-update && xdg-user-dirs-gtk-update &

    # enable numlock (do not use on laptops without numpads)
    #_command numlockx && numlockx &

    # screen saver
    #_command xautolock && xautolock -time 30 -locker blurlock & # lock screen after 30 minutes

    # tell firefox to match theme
    #_command ff-theme-util && ff-theme-util &

    # clipmenu
    _command clipmenud && clipmenud &

    # eject-applet
    #_command eject-applet && eject-applet &

    # set cursor theme
    _command fix_xcursor && fix_xcursor &

    # hide mouse when not in use
    _command unclutter && unclutter &

    # wallpaper manager
    _command nitrogen && nitrogen --restore &

    # rebuild wm menu
    #sleep 10 && _command mmaker && mmaker --force openbox &
fi

# auto-start custom applications
[[ -f "${HOME}/.config/bspwm/bspwmrc-applications" ]] && source "${HOME}/.config/bspwm/bspwmrc-applications"

#===============================================================================
# End of File
#===============================================================================
