#!/usr/bin/env bash
#===============================================================================
# .config/bspwm/bspwmrc
#
# Binary Space Partitioning Window Manager (bspwm) configuration.
#
# Reference: https://github.com/baskerville/bspwm
# Reference: https://gitlab.com/protesilaos/dotfiles/-/blob/v2.2.0/bspwm/.config/bspwm/bspwmrc
#===============================================================================

# check if executable command is found in the path
_command() {
    command -v "$1" >/dev/null 2>&1
}

# bspc config
_bc() {
    bspc config "$@"
}

# bspc rule --add
_br() {
    bspc rule --add "$@"
}

#-------------------------------------------------------------------------------
# Configuration
#-------------------------------------------------------------------------------

# global settings
_bc split_ratio                0.5
#_bc stacked_layout             true
_bc stacked_direction          east
_bc stacked_ratio              0.7
_bc automatic_scheme           alternate
#_bc initial_polarity           first_child
_bc initial_polarity           second_child
_bc removal_adjustment         true
_bc borderless_monocle         false
_bc gapless_monocle            false
_bc single_monocle             true
_bc click_to_focus             any
_bc swallow_first_click        false
_bc focus_follows_pointer      false
_bc pointer_follows_monitor    true
_bc ignore_ewmh_focus          true
_bc ignore_ewmh_fullscreen     none
_bc ignore_ewmh_struts         false
_bc center_pseudo_tiled        true
_bc honor_size_hints           true
_bc remove_disabled_monitors   true
_bc remove_unplugged_monitors  true
_bc merge_overlapping_monitors true

# monitor and desktop settings
_bc top_padding                0
_bc right_padding              0
#_bc bottom_padding             0
#_bc bottom_padding             30       # room for tint2 system bar
_bc bottom_padding             22       # room for xfce/eww system bar
_bc left_padding               0

# desktop settings
_bc window_gap                 4

# node settings
_bc border_width               4

# pointer bindings
_bc pointer_modifier           mod4
_bc pointer_action1            resize_side
_bc pointer_action1            resize_corner
_bc pointer_action3            move

# default colors
#_bc normal_border_color        "#30302f"
#_bc active_border_color        "#474645"
#_bc focused_border_color       "#817f7f"
#_bc presel_feedback_color      "#f4d775"

# custom colors
_bc normal_border_color        "#4c566a"
_bc active_border_color        "#1e1e1e"
_bc focused_border_color       "#5e81ac"
_bc presel_feedback_color      "#5e81ac"

#-------------------------------------------------------------------------------
# Monitors
#-------------------------------------------------------------------------------

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12
#bspc monitor -d "1  " "2  " "3  " "4  " "5  " "6  " "7  " "8  " "9  " "10  "
#bspc monitor -d "1  " "2  " "3  " "4  " "5  " "6  " "7  " "8  " "9  " "10  "

#-------------------------------------------------------------------------------
# Application Desktop Assignments
#-------------------------------------------------------------------------------

# 1: Terminal
#bspc desktop 1 --layout stacked
#_br 'Alacritty' desktop='^1' follow=on
#_br 'personal:Alacritty' desktop='^1' follow=on

# 2: Editor
#bspc desktop 2 --layout stacked
_br 'Emacs' desktop='^2' follow=on
_br 'personal:Emacs' desktop='^2' follow=on

# 3: Email
bspc desktop 3 --layout monocle
_br 'thunderbird' desktop='^3' follow=on
_br 'personal:thunderbird' desktop='^3' follow=on
_br 'betterbird' desktop='^3' follow=on
_br 'personal:betterbird' desktop='^3' follow=on
_br 'ms-outlook-nativefier' desktop='^3' follow=on
_br 'personal:ms-outlook-nativefier' desktop='^3' follow=on

# 4: Browser
bspc desktop 4 --layout monocle
_br 'firefox' desktop='^4' follow=on
_br 'personal:firefox' desktop='^4' follow=on
_br 'LibreWolf' desktop='^4' follow=on
_br 'personal:LibreWolf' desktop='^4' follow=on
_br 'Brave-browser' desktop='^4' follow=on
_br 'personal:Brave-browser' desktop='^4' follow=on
_br 'vivaldi-stable' desktop='^4' follow=on
_br 'personal:vivaldi-stable' desktop='^4' follow=on
_br 'gopherus-sdl' desktop='^4' follow=on
_br 'personal:gopherus-sdl' desktop='^4' follow=on

# 5: File Manager
#bspc desktop 5 --layout stacked
_br 'Thunar' desktop='^5' follow=on
_br 'personal:Thunar' desktop='^5' follow=on
_br 'Pcmanfm' desktop='^5' follow=on
_br 'personal:Pcmanfm' desktop='^5' follow=on
_br 'Spacefm' desktop='^5' follow=on
_br 'personal:Spacefm' desktop='^5' follow=on
_br 'Org.gnome.Nautilus' desktop='^5' follow=on
_br 'personal:Org.gnome.Nautilus' desktop='^5' follow=on
#_br 'Filezilla' desktop='^5' follow=on
#_br 'personal:Filezilla' desktop='^5' follow=on
_br 'Transmission-gtk' desktop='^5' follow=on
_br 'personal:Transmission-gtk' desktop='^5' follow=on
#_br 'balena-etcher-electron' desktop='^5' follow=on
#_br 'personal:balena-etcher-electron' desktop='^5' follow=on
#_br 'Ghb' desktop='^5' follow=on
#_br 'personal:Ghb' desktop='^5' follow=on

# 6: Chat
bspc desktop 6 --layout tiled
_br 'Slack' desktop='^6' follow=on
_br 'personal:Slack' desktop='^6' follow=on
_br 'discord' desktop='^6' follow=on
_br 'personal:discord' desktop='^6' follow=on

# 7: More Chat
#bspc desktop 7 --layout stacked
_br 'Pidgin' desktop='^7' follow=on
_br 'personal:Pidgin' desktop='^7' follow=on
_br 'Tootle' desktop='^7' follow=on
_br 'personal:Tootle' desktop='^7' follow=on
_br 'Com.github.bleakgrey.tootle' desktop='^7' follow=on
_br 'personal:Com.github.bleakgrey.tootle' desktop='^7' follow=on
_br 'Element' desktop='^7' follow=on
_br 'personal:Element' desktop='^7' follow=on
_br 'dev.geopjr.Tuba' desktop='^7' follow=on
_br 'personal:dev.geopjr.Tuba' desktop='^7' follow=on
_br 'Gajim' desktop='^7' follow=on
_br 'personal:Gajim' desktop='^7' follow=on
_br 'Hyperspace Desktop' desktop='^7' follow=on
_br 'personal:Hyperspace Desktop' desktop='^7' follow=on
_br 'android-messages-desktop' desktop='^7' follow=on
_br 'personal:android-messages-desktop' desktop='^7' follow=on
_br 'teams-for-linux' desktop='^7' follow=on
_br 'personal:teams-for-linux' desktop='^7' follow=on

# 8: Development
bspc desktop 8 --layout monocle
_br 'jetbrains-idea' desktop='^8' follow=on
_br 'personal:jetbrains-idea' desktop='^8' follow=on
_br 'jetbrains-idea-ce' desktop='^8' follow=on
_br 'personal:jetbrains-idea-ce' desktop='^8' follow=on
_br 'jetbrains-studio' desktop='^8' follow=on
_br 'personal:jetbrains-studio' desktop='^8' follow=on
#_br 'dosbox' desktop='^8' follow=on
#_br 'personal:dosbox' desktop='^8' follow=on
#_br 'BasiliskII' desktop='^8' follow=on
#_br 'personal:BasiliskII' desktop='^8' follow=on
_br 'VirtualBox Manager' desktop='^8' follow=on
_br 'personal:VirtualBox Manager' desktop='^8' follow=on
_br 'VirtualBox Machine' desktop='^8' follow=on
_br 'personal:VirtualBox Machine' desktop='^8' follow=on

# 9: Image, Video, and Audio
#bspc desktop 9 --layout stacked
_br 'Chromium-browser' desktop='^9' follow=on
_br 'personal:Chromium-browser' desktop='^9' follow=on
_br 'Google-chrome' desktop='^9' follow=on
_br 'personal:Google-chrome' desktop='^9' follow=on
_br 'Gimp-2.10' desktop='^9' follow=on
_br 'personal:Gimp-2.10' desktop='^9' follow=on
_br 'Qmmp' desktop='^9' follow=on
_br 'personal:Qmmp' desktop='^9' follow=on
_br 'mplayer2' desktop='^9' follow=on
_br 'personal:mplayer2' desktop='^9' follow=on
_br 'Lollypop' desktop='^9' follow=on
_br 'personal:Lollypop' desktop='^9' follow=on
_br 'LBRY' desktop='^9' follow=on
_br 'personal:LBRY' desktop='^9' follow=on
_br 'spotify' desktop='^9' follow=on
_br 'personal:spotify' desktop='^9' follow=on
_br 'bluejeans-v2' desktop='^9' follow=on
_br 'personal:bluejeans-v2' desktop='^9' follow=on

# 10: Games
#bspc desktop 9 --layout stacked
#_br 'syncterm' desktop='^10' follow=on
#_br 'personal:syncterm' desktop='^10' follow=on

# 11: Virtual Machine 1

# 12: Virtual Machine 2

#-------------------------------------------------------------------------------
# Application Rules
#-------------------------------------------------------------------------------

# tiled applications
_br 'Emacs' state=tiled
_br 'personal:Emacs' state=tiled

# fullscreen applications
_br 'bluejeans-v2' state=fullscreen
_br 'personal:bluejeans-v2' state=fullscreen
_br 'Evince' state=fullscreen
_br 'personal:Evince' state=fullscreen
_br 'Ghb' state=fullscreen
_br 'personal:Ghb' state=fullscreen
_br 'Gimp-2.10' state=fullscreen
_br 'personal:Gimp-2.10' state=fullscreen
#_br 'jetbrains-idea' state=fullscreen
#_br 'personal:jetbrains-idea' state=fullscreen
#_br 'jetbrains-idea-ce' state=fullscreen
#_br 'personal:jetbrains-idea-ce' state=fullscreen
#_br 'jetbrains-studio' state=fullscreen
#_br 'personal:jetbrains-studio' state=fullscreen
#_br 'Microsoft Teams' state=fullscreen
#_br 'personal:Microsoft Teams' state=fullscreen
_br 'mplayer2' state=fullscreen
_br 'personal:mplayer2' state=fullscreen
#_br 'spotify' state=fullscreen
#_br 'personal:spotify' state=fullscreen
_br 'vlc' state=fullscreen
_br 'personal:vlc' state=fullscreen
_br 'VirtualBox Manager' state=fullscreen
_br 'personal:VirtualBox Manager' state=fullscreen
_br 'VirtualBox Machine' state=fullscreen
_br 'personal:VirtualBox Machine' state=fullscreen
_br 'w40k.exe' state=fullscreen
_br 'personal:w40k.exe' state=fullscreen

# floating applications
_br 'alsamixer' state=floating center=true
_br 'personal:alsamixer' state=floating center=true
_br 'arandr' state=floating center=true
_br 'personal:arandr' state=floating center=true
_br 'Audacious' state=floating sticky=true
_br 'personal:Audacious' state=floating sticky=true
_br 'balena-etcher-electron' state=floating center=true
_br 'personal:balena-etcher-electron' state=floating center=true
_br 'BasiliskII' state=floating center=true
_br 'personal:BasiliskII' state=floating center=true
_br '.blueman-manager-wrapped' state=floating center=true
_br 'personal:.blueman-manager-wrapped' state=floating center=true
_br 'Calamares' state=floating center=true
_br 'personal:Calamares' state=floating center=true
_br 'Clipgrab' state=floating center=true
_br 'personal:Clipgrab' state=floating center=true
_br 'Cisco AnyConnect Secure Mobility Client' state=floating center=true
_br 'personal:Cisco AnyConnect Secure Mobility Client' state=floating center=true
#_br 'dosbox' state=floating center=true
#_br 'personal:dosbox' state=floating center=true
_br 'feh' state=floating center=true
_br 'personal:feh' state=floating center=true
_br 'File Transfer*' state=floating center=true
_br 'personal:File Transfer*' state=floating center=true
_br 'Font-manager' state=floating center=true
_br 'personal:Font-manager' state=floating center=true
_br 'Font-viewer' state=floating center=true
_br 'personal:Font-viewer' state=floating center=true
_br 'Galculator' state=floating center=true
_br 'personal:Galculator' state=floating center=true
_br 'Gnome-disks' state=floating center=true
_br 'personal:Gnome-disks' state=floating center=true
_br 'GParted' state=floating center=true
_br 'personal:GParted' state=floating center=true
_br 'Gxmessage' state=floating center=true
_br 'personal:Gxmessage' state=floating center=true
_br '(?i)gsimplecal' state=floating center=true
_br 'personal:(?i)gsimplecal' state=floating center=true
_br 'iwgtk' state=floating center=true
_br 'personal:iwgtk' state=floating center=true
#_br 'jetbrains-idea' state=floating center=true
#_br 'personal:jetbrains-idea' state=floating center=true
#_br 'jetbrains-idea-ce' state=floating center=true
#_br 'personal:jetbrains-idea-ce' state=floating center=true
#_br 'jetbrains-studio' state=floating center=true
#_br 'personal:jetbrains-studio' state=floating center=true
_br 'Lightdm-gtk-greeter-settings' state=floating center=true
_br 'personal:Lightdm-gtk-greeter-settings' state=floating center=true
_br 'Lxappearance' state=floating center=true
_br 'personal:Lxappearance' state=floating center=true
_br 'Manjaro-hello' state=floating center=true
_br 'personal:Manjaro-hello' state=floating center=true
_br 'Manjaro Settings Manager' state=floating center=true
_br 'personal:Manjaro Settings Manager' state=floating center=true
_br 'mpv' state=floating center=true sticky=on
_br 'personal:mpv' state=floating center=true sticky=on
_br 'MuseScore: Play Panel' state=floating center=true sticky=on
_br 'personal:MuseScore: Play Panel' state=floating center=true sticky=on
_br 'Nitrogen' state=floating center=true
_br 'personal:Nitrogen' state=floating center=true
_br 'oblogout' state=floating center=true
_br 'personal:oblogout' state=floating center=true
_br 'octopi' state=floating center=true
_br 'personal:octopi' state=floating center=true
_br 'About Pale Moon' state=floating center=true
_br 'personal:About Pale Moon' state=floating center=true
_br 'Pamac-manager' state=floating center=true
_br 'personal:Pamac-manager' state=floating center=true
_br 'Paprefs' state=floating center=true
_br 'personal:Paprefs' state=floating center=true
_br 'Pavucontrol' state=floating center=true
_br 'personal:Pavucontrol' state=floating center=true
_br 'Qmmp' state=floating sticky=true
_br 'personal:Qmmp' state=floating sticky=true
_br 'qt5ct' state=floating sticky=true
_br 'personal:qt5ct' state=floating sticky=true
_br 'Qtconfig-qt4' state=floating sticky=true
_br 'personal:Qtconfig-qt4' state=floating sticky=true
_br 'Simple-scan' state=floating center=true
_br 'personal:Simple-scan' state=floating center=true
_br '(?i)System-config-printer.py' state=floating center=true
_br 'personal:(?i)System-config-printer.py' state=floating center=true
_br 'Skype' state=floating center=true
_br 'personal:Skype' state=floating center=true
_br 'syncterm' state=floating center=true
_br 'personal:syncterm' state=floating center=true
_br 'Thus' state=floating center=true
_br 'personal:Thus' state=floating center=true
_br 'Tint2conf' state=floating center=true
_br 'personal:Tint2conf' state=floating center=true
_br 'Timeset-gui' state=floating center=true
_br 'personal:Timeset-gui' state=floating center=true
_br '(?i)virtualbox' state=floating center=true
_br 'personal:(?i)virtualbox' state=floating center=true
_br 'X48' state=floating center=true
_br 'personal:X48' state=floating center=true
_br 'Xfburn' state=floating center=true
_br 'personal:Xfburn' state=floating center=true
_br 'Xfce4-settings-manager' state=floating center=true
_br 'personal:Xfce4-settings-manager' state=floating center=true
_br 'Yad' state=floating center=true
_br 'personal:Yad' state=floating center=true

#-------------------------------------------------------------------------------
# Auto-Start Standard Applications
#-------------------------------------------------------------------------------

# # https://wiki.archlinux.org/title/bspwm#Problems_with_Java_applications
# # set window manager name so that java applications work
# wmname LG3D
# # fix java app not refreshing issue in tiling window managers
# export _JAVA_AWT_WM_NONREPARENTING=1

# check if executable command is found in the path
_command() {
    command -v "$1" >/dev/null 2>&1
}

# # delay running a command (SECONDS COMMAND)
# _delay() {
#     local delay=$1
#     shift
#     sleep ${delay} && eval "$@"
# }

# simple x hotkey daemon
# (might have been started already by .xprofile)
[[ -f "${HOME}/bin/run-sxhkd" ]] && ${HOME}/bin/run-sxhkd &

# xfce settings
#_command xfsettingsd && xfsettingsd &

# ssh-agent
#_command ssh-agent && ssh-agent &
#_command ssh-add && ssh-add &

# key bindings
#xmodmap "${HOME}/.xmodmaprc" &
#set-xkb &
#xbindkeys &

# policykit authentation agent
if [[ -x /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 ]] ; then
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
    #eval "$(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)" &
fi
_command lxpolkit && lxpolkit &

# compositor
_command picom && picom -b &

# system bar
[[ -f "${HOME}/bin/system-bar" ]] && source "${HOME}/bin/system-bar"

# system wallpaper displays
[[ -f "${HOME}/bin/system-wallpaper-displays" ]] && source "${HOME}/bin/system-wallpaper-displays"

# full-screen task-switcher
#_command skippy-xd && skippy-xd --config "${HOME}/.config/skippy-xd/skippy-xd.rc" --start-daemon &

# localize user system folders
#_command xdg-user-dirs-gtk-update && xdg-user-dirs-gtk-update &

# enable numlock (do not use on laptops without numpads)
#_command numlockx && numlockx &

# screen saver
#_command xautolock && xautolock -time 30 -locker blurlock & # lock screen after 30 minutes

# tell firefox to match theme
#_command ff-theme-util && ff-theme-util &

# clipmenu
_command clipmenud && clipmenud &

# eject-applet
#_command eject-applet && eject-applet &

# set cursor theme
_command fix_xcursor && fix_xcursor &

# hide mouse when not in use
_command unclutter && unclutter &

# wallpaper manager
_command nitrogen && nitrogen --restore &

# rebuild wm menu
#sleep 10 && _command mmaker && mmaker --force openbox &

# # qubes os specific items
# # (found in /etc/xdg/autostart)
# if [[ "$(uname -n)" == "dom0" ]] ; then
#     # qubes qrexec policy agent
#     /usr/lib/qubes/qrexec-policy-agent-autostart &
#     # qubes application menu
#     (systemctl --user import-environment XDG_CURRENT_DESKTOP XDG_DATA_HOME XDG_CONFIG_HOME XDG_STATE_HOME XDG_DATA_DIRS XDG_CONFIG_DIRS \
    #                XDG_CACHE_HOME XDG_RUNTIME_DIR XDG_SESSION_CLASS XDG_SESSION_DESKTOP XDG_SESSION_ID XDG_SESSION_PATH XDG_SESSION_TYPE
#      systemctl --user start qubes-app-menu) &
#     # qubes window icon receiver
#     /usr/lib/qubes/icon-receiver &
#     # retry qubes rpc prompts for input devices
#     /usr/bin/qubes-input-trigger --all &
#     # notify qubes vms about screen layout changes
#     /usr/libexec/qubes/watch-screen-layout-changes qvm-start-gui --notify-monitor-layout --all &
#     # update qubes specific xfce config
#     /usr/lib/qubes/update-xfce-config &
# fi

# auto-start custom applications
[[ -f "${HOME}/.config/bspwm/bspwmrc-applications" ]] && source "${HOME}/.config/bspwm/bspwmrc-applications"

#===============================================================================
# End of File
#===============================================================================
