arch = {
  packages = [
    "chatbox-bin",
    "hfdownloader",
    "ik-llama.cpp-cuda",
    "imaginer",
    "lmstudio",
    "ollama",
    "ollama-docs",
    "fortunecraft",
    "upscayl-bin",

  ]
}


