arch = [
    "acme",
    "android-sdk-build-tools",
    "android-sdk-platform-tools",
    "android-studio",
    "android-tools",
    "android-udev",
    "autoconf",
    "autoconf-archive",
    "automake",
    "better-adb-sync-git",
    "binutils",
    "binutils-ia16",
    "bison",
    "bucklespring",
    "cc65",
    "ccache",
    "chibi-scheme",
    "cht.sh-git",
    "clang",
    "clisp",
    "cmake",
    "code",
    "csvkit",
    "ctags",
    "dbeaver",
    "debtap",
    "deno",
    "diffutils",
    "djgpp-binutils",
    "djgpp-djcrx-bootstrap",
    "djgpp-gcc",
    "dotnet-runtime",
    "dotnet-sdk",
    "flex",
    "fpc",
    "freebasic",
    "gcc",
    "gcc-ia16",
    "glibc",
    "gmp",
    "gnuplot",
    "go",
    "gpp",
    "gradle",
    "gradle-doc",
    "graphviz",
    "guile",
    "hq",
    "htmlq",
    "intellij-idea-community-edition",
    "ipython",
    "jdk-openjdk",
    "jq",
    "jqp",
    "jre",
    "kotlin",
    "lazarus",
    "lazarus-qt6",
    "lazygit",
    "lazyjournal",
    "libedit",
    "libmpc",
    "m4",
    "mpfr",
    "multimarkdown",
    "nasm",
    "openwatcom-v2",
    "pandoc-bin",
    "patch",
    "perl-lwp-protocol-https",
    "perl-text-aspell",
    "plantuml",
    "pup",
    "qt5-tools",
    "qt6-tools",
    "racket",
    "regina-rexx",
    "regina-rexx-doc",
    "ruby",
    "ruby-lsp",
    "rust",
    "sbcl",
    "shellcheck",
    "swift-bin",
    "tass64",
    "terminology",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-latexextra",
    "texlive-pictures",
    "tokei",
    "vasm",
    "vlang",
    "vlink",
    "x16-docs-bin",
    "x16-emulator-bin",
    "x16-rom-bin",
    "yq",
    "zlib",
]

