arch = [
    "basiliskii-git",
    "dosbox",
    "fs-uae",
    "fs-uae-launcher",
    "linapple-git",
    "mame",
    "minivmac",
    "vice",
    "wine",
    "wine-gecko",
    "wine-mono",
    "winetricks",
]

