arch = {
  packages = [
    "0ad",
    "celeste64-bin",
    "dwarffortress",
    "luanti",
    "lutris",
    "osu-lazer-bin",
    "pingus",
    "pysolfc",
    "rocksndiamonds",
    "steam",
    "supertux",
    "supertuxkart",
    "tuxracer",
    "unciv-bin",
    "wesnoth",
    "xonotic",

  ]
}


