arch = [
    "betterbird-bin",
    "brave-bin",
    "bruno-bin",
    "carburetor",
    "copyparty",
    "dino",
    "discord",
    "element-desktop",
    "filezilla",
    "flashplugin",
    "gajim",
    "gnu-netcat",
    "gopherus",
    "gossip-bin",
    "hyperspace-bin",
    "kristall",
    "ladybird",
    "localsend-bin",
    "magic-wormhole",
    "nheko",
    "nyxt",
    "opensnitch",
    "pepper-flash",
    "pidgin",
    "quassel-client",
    "simplex-chat-bin",
    "slack-bin",
    "surf",
    "surfraw",
    "syncterm-git",
    "telegram-desktop",
    "thunderbird-bin",
    "tor-browser-bin",
    "tractor",
    "transmission-gtk",
    "tribler-bin",
    "tuba",
    "vdhcoapp",
    "waterfox-bin",
]

