arch = {
  packages = [
    "audacious",
    "audacious-plugins",
    "brave-bin",
    "cliamp",
    "cmus",
    "cool-retro-term",
    "cowsay",
    "ffmpeg",
    "figlet",
    "font-manager",
    "gnuplot",
    "graphviz",
    "lazygit",
    "lazyjournal",
    "links",
    "lynx",
    "mc",
    "mplayer",
    "mpv",
    "papers",
    "plantuml",
    "ranger",
    "speedtest-cli",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-latexextra",
    "texlive-pictures",
    "translate-shell",
    "vlc",
    "w3m",
    "wordgrinder",
    "x48ng",
    "ymuse",
    "zlib",

  ]
}


