arch = {
  packages = [
    "7zip",
    "aalib",
    "acme",
    "aha",
    "alacritty",
    "android-sdk-build-tools",
    "android-sdk-platform-tools",
    "android-studio",
    "android-tools",
    "android-udev",
    "arch-wiki-cli",
    "arch-wiki-docs",
    "asciiquarium",
    "aspell-en",
    "audacious",
    "autoconf",
    "autoconf-archive",
    "automake",
    "bandwhich",
    "base",
    "base-devel",
    "basiliskii-git",
    "bb",
    "better-adb-sync-git",
    "binutils",
    "bison",
    "bitwarden",
    "bluez",
    "bluez-utils",
    "bpytop",
    "brave-bin",
    "btop",
    "bucklespring",
    "bullshit",
    "bzip2",
    "cbonsai",
    "cc65",
    "ccache",
    "chaotic-keyring",
    "chaotic-mirrorlist",
    "chatbox-bin",
    "checksec",
    "chibi-scheme",
    "cht.sh-git",
    "cifs-utils",
    "clang",
    "cliamp",
    "clisp",
    "cmake",
    "cmatrix",
    "cmus",
    "cndrvcups-lb-bin",
    "code",
    "cool-retro-term",
    "cowsay",
    "csvkit",
    "ctags",
    "cups",
    "curl",
    "dbeaver",
    "debtap",
    "debugedit",
    "deno",
    "diffutils",
    "direnv",
    "dos2unix",
    "dosbox",
    "dosfstools",
    "dotnet-runtime",
    "dotnet-sdk",
    "duf",
    "emacs",
    "ethtool",
    "evince",
    "exfatprogs",
    "expac",
    "fastfetch",
    "ffmpeg",
    "figlet",
    "firefox",
    "flex",
    "font-manager",
    "fortunecraft",
    "fortune-mod-archlinux",
    "fortune-mod-asoiaf",
    "fortune-mod-bofh-excuses",
    "fortune-mod-confucius",
    "fortune-mod-farscape",
    "fortune-mod-firefly",
    "fortune-mod-futurama",
    "fortune-mod-hackers",
    "fortune-mod-hitchhiker",
    "fortune-mod-montypython",
    "fortune-mod-off",
    "fortune-mod-starwars",
    "fortune-mod-xfiles",
    "fpc",
    "freebasic",
    "fs-uae",
    "fs-uae-launcher",
    "fzf",
    "gcc",
    "genact",
    "git",
    "github-desktop",
    "glibc",
    "gmp",
    "gnome-settings-daemon",
    "gnuplot",
    "go",
    "gpp",
    "gradle",
    "gradle-doc",
    "graphviz",
    "guile",
    "gum",
    "gvfs",
    "gvfs-smb",
    "hacker-typer",
    "helvum",
    "hfdownloader",
    "hfsprogs",
    "hollywood",
    "htmlq",
    "htop",
    "hunspell-en_us",
    "id3lib",
    "iftop",
    "imagemagick",
    "imaginer",
    "inetutils",
    "intellij-idea-community-edition",
    "inxi",
    "iperf",
    "ipython",
    "ispell",
    "jdk-openjdk",
    "jq",
    "jqp",
    "jre",
    "keychain",
    "kotlin",
    "languagetool",
    "lavat-git",
    "lazarus",
    "lazarus-qt6",
    "lazygit",
    "lazyjournal",
    "ldns",
    "less",
    "lhasa",
    "libedit",
    "libmpc",
    "libpng12",
    "linapple-git",
    "links",
    "lmstudio-bin",
    "lolcat",
    "lsb-release",
    "lsof",
    "lxappearance",
    "lynx",
    "m4",
    "mame",
    "man-db",
    "man-pages",
    "mc",
    "metapac",
    "minivmac",
    "moreutils",
    "mousepad",
    "mpc",
    "mpd",
    "mpdris2",
    "mpfr",
    "mplayer",
    "mpv",
    "mtools",
    "multimarkdown",
    "multitail",
    "nano",
    "nasm",
    "neofetch",
    "neoss",
    "netkit-bsd-finger",
    "net-tools",
    "nfs-utils",
    "nitch",
    "nmap",
    "no-more-secrets",
    "noto-fonts",
    "noto-fonts-emoji",
    "ntfs-3g",
    "ocaml-csexp",
    "ollama",
    "ollama-docs",
    "openssl",
    "openssl-1.1",
    "openwatcom-v2",
    "orpie",
    "pacman-contrib",
    "pamixer",
    "pandoc-bin",
    "papers",
    "paru",
    "patch",
    "perl-lwp-protocol-https",
    "perl-text-aspell",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "pipewire-qubes",
    "pkgfile",
    "plantuml",
    "plocate",
    "pup",
    "python",
    "python-urllib3",
    "qubes-vm-dependencies",
    "qubes-vm-recommended",
    "qubes-vm-repo",
    "quicklisp",
    "racket",
    "ranger",
    "regina-rexx",
    "regina-rexx-doc",
    "remind",
    "rig",
    "ripgrep",
    "rsync",
    "ruby",
    "ruby-lsp",
    "rust",
    "rxvt-unicode",
    "samba",
    "sbcl",
    "screen",
    "scrub",
    "shc",
    "shellcheck",
    "shell-color-scripts-git",
    "sl",
    "smbclient",
    "speedtest-cli",
    "stow",
    "sudo",
    "swift-bin",
    "sysz",
    "tass64",
    "terminology",
    "terminus-font",
    "texlive-bin",
    "texlive-fontsextra",
    "texlive-fontsrecommended",
    "texlive-latexextra",
    "texlive-pictures",
    "texlive-plaingeneric",
    "the_silver_searcher",
    "thunar",
    "thunar-volman",
    "thunderbird",
    "tldr",
    "tmux",
    "tmux-plugin-manager",
    "tokei",
    "traceroute",
    "translate-shell",
    "ttf-bitstream-vera",
    "ttf-dejavu",
    "ttf-inconsolata",
    "ttf-linux-libertine",
    "tty-clock",
    "ufiformat",
    "unipicker",
    "unison",
    "unzip",
    "upscayl-bin",
    "usbutils",
    "vasm",
    "vice",
    "vim",
    "vlang",
    "vlc",
    "vlink",
    "vtop",
    "w3m",
    "wget",
    "wine",
    "wine-gecko",
    "wine-mono",
    "winetricks",
    "wipe",
    "wireplumber",
    "woeusb",
    "wordgrinder",
    "x48ng",
    "xfce4-terminal",
    "xorg-server",
    "xterm",
    "ydotool",
    "ymuse-bin",
    "yq",
    "zip",
    "zlib",

  ]
}


