arch = [
    "asunder",
    "audacious",
    "balena-etcher",
    "bitwarden",
    "blanket",
    "brasero",
    "celluloid",
    "cherrytree",
    "cool-retro-term",
    "czkawka-gui",
    "deadbeef",
    "dmg2img",
    "easytag",
    "engrampa",
    "fim",
    "flameshot",
    "font-manager",
    "gnome-multi-writer",
    "gparted",
    "gphoto2",
    "gtkimageview",
    "handbrake",
    "isoimagewriter",
    "libaacs",
    "libation",
    "libbluray",
    "libdvdcss",
    "livecaptions",
    "makemkv",
    "mediawriter",
    "meld",
    "mplayer",
    "mpv",
    "mupdf-tools",
    "notepadqq",
    "papers",
    "qmmp",
    "qmplay2",
    "rpi-imager",
    "scrcpy",
    "sox",
    "sxiv",
    "timg",
    "ventoy-bin",
    "virt-viewer",
    "vlc",
    "vlc-plugins-all",
    "x48ng",
    "xpdf",
    "xarchiver",
    "ymuse-bin",
    "zathura",
]

