#!/usr/bin/env bash
#===============================================================================
# bspwmrc-applications
#
# Binary Space Partitioning Window Manager (bspwm) auto-start applications
# script.
#
# Reference:  https://github.com/baskerville/bspwm
#===============================================================================

# check if executable command is found in the path
_command() {
    command -v "$1" > /dev/null 2>&1
}

# delay running a command (SECONDS COMMAND)
_delay() {
    local delay=$1
    shift
    sleep ${delay} && eval "$@"
}

# initialize background applications and services
_command xscreensaver && xscreensaver -no-splash &
#_command xautolock && xautolock -time 30 -locker blurlock & # lock screen after 30 minutes
#_command xautolock && xautolock -time 30 -locker 'xscreensaver-command -lock' & # lock screen after 30 minutes
#_command mpd && mpd ${HOME}/.mpd/mpd.conf &
#_command dropbox && dropbox start &
#_command barriers && barriers --config ${HOME}/.barrier.conf &
#_command barrierc && barrierc SERVER &
#_command emacs && emacs --daemon &

# initialize foreground applications
#_command alacritty && alacritty -e ${HOME}/bin/run-screen &
_command alacritty && _delay 20 bspc node --to-desktop 1 --follow alacritty -e ${HOME}/bin/run-screen &
_command emacs && _delay 1 emacs &
#_command slack && _delay 1 slack &
#_command thunderbird && _delay 20 thunderbird &
_command firefox && _delay 1 firefox &
#_command vivaldi && _delay 1 vivaldi &
#_command chromium && _delay 1 chromium &
#_command pcmanfm && _delay 1 pcmanfm &
_command spacefm && _delay 1 spacefm &
#_command thunar && _delay 1 thunar &
#_command idea && _delay 20 idea &
#_command discord && _delay 1 discord &
#_command pidgin && _delay 1 pidgin &
#_command gajim && _delay 40 gajim &
#_command tootle && _delay 20 tootle &
#_command com.github.bleakgrey.tootle && _delay 20 com.github.bleakgrey.tootle &
#_command lbry && _delay 1 lbry &
#_command syncterm && _delay 1 syncterm &

#===============================================================================
# End of File
#===============================================================================
