#!/usr/bin/env bash
METRIC=0                                # should be 0 for F or 1 for C

if [[ $# -ne 1 ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]] ; then
    echo "Usage: $(basename $0) LOCATION_CODE"
    echo "  LOCATION_CODE  ZIP Code"
    exit 1
fi

curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=${METRIC}&locCode=$1" | perl -ne '
    use utf8;
    binmode(STDOUT, ":utf8");
    if (/\<title\>Currently: /) {
        chomp;
        /\<title\>Currently: (.*)?\<\/title\>/;
        my @values = split(":", $1);
        my $desc = $values[0];
        my $temp = $values[1];
        my $icon = "";
        for ($desc) {
            if("Sunny") { $icon = " "; }
            elsif("Mostly Sunny") { $icon = " "; }
            elsif("Partly Sunny") { $icon = " "; }
            elsif("Hazy Sunshine") { $icon = " "; }
            elsif("Hot") { $icon = " "; }
            elsif("Intermittent Clouds") { $icon = " "; }
            elsif("Cloudy") { $icon = " "; }
            elsif("Mostly Cloudy") { $icon = " "; }
            elsif("Dreary (Overcast)") { $icon = " "; }
            elsif("Fog") { $icon = " "; }
            elsif("Rain") { $icon = " "; }
            elsif("Showers") { $icon = " "; }
            elsif("Partly Cloudy w/ Showers") { $icon = " "; }
            elsif("Mostly Cloudy w/ Showers") { $icon = " "; }
            elsif("Partly Sunny w/ Showers") { $icon = " "; }
            elsif("T-Storms") { $icon = " "; }
            elsif("Mostly Cloudy w/ T-Storms") { $icon = " "; }
            elsif("Partly Cloudy w/ T-Storms") { $icon = " "; }
            elsif("Partly Sunny w/ T-Storms") { $icon = " "; }
            elsif("Windy") { $icon = " "; }
            elsif("Flurries") { $icon = " "; }
            elsif("Mostly Cloudy w/ Flurries") { $icon = " "; }
            elsif("Snow") { $icon = " "; }
            elsif("Mostly Cloudy w/ Snow") { $icon = " "; }
            elsif("Partly Sunny w/ Flurries") { $icon = " "; }
            elsif("Ice") { $icon = " "; }
            elsif("Sleet") { $icon = " "; }
            elsif("Freezing Rain") { $icon = " "; }
            elsif("Rain and Snow") { $icon = " "; }
            elsif("Cold") { $icon = " "; }
            elsif("Clear") { $icon = " "; }
            elsif("Mostly Clear") { $icon = " "; }
            elsif("Partly Cloudy") { $icon = " "; }
            elsif("Intermittent Clouds") { $icon = " "; }
            elsif("Hazy Moonlight") { $icon = " "; }
            else { system("notify-send -u critical \"Weather: $desc\""); }
        }
        print "$icon$temp";
    }'
