#!/usr/bin/env bash
METRIC=0                                # should be 0 for F or 1 for C

if [[ $# -ne 1 ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]] ; then
    echo "Usage: $(basename $0) LOCATION_CODE"
    echo "  LOCATION_CODE  ZIP Code"
    exit 1
fi

curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=${METRIC}&locCode=$1" | perl -ne '
    use utf8;
    binmode(STDOUT, ":utf8");
    if (/Currently/) {
        chomp;
        /\<title\>Currently: (.*)?\<\/title\>/;
        my @values = split(":", $1);
        my $desc = $values[0];
        my $temp = $values[1];
        my $icon = "";
        if ($desc eq "Sunny" || $desc eq "Mostly Sunny" || $desc eq "Partly Sunny") {
            $icon = " ";
        }
        if ($desc eq "Hazy Sunshine" || $desc eq "Hot") {
            $icon = " ";
        }
        if ($desc eq "Intermittent Clouds") {
            $icon = " ";
        }
        if ($desc eq "Mostly Cloudy" || $desc eq "Cloudy") {
            $icon = " ";
        }
        if ($desc eq "Dreary (Overcast)" || $desc eq "Fog") {
            $icon = " ";
        }
        if ($desc eq "Rain") {
            $icon = " ";
        }
        if ($desc eq "Showers" || $desc eq "Partly Cloudy w/ Showers" || $desc eq "Mostly Cloudy w/ Showers") {
            $icon = " ";
        }
        if ($desc eq "Partly Sunny w/ Showers") {
            $icon = " ";
        }
        if ($desc eq "T-Storms") {
            $icon = " ";
        }
        if ($desc eq "Mostly Cloudy w/ T-Storms" || $desc eq "Partly Cloudy w/ T-Storms") {
            $icon = " ";
        }
        if ($desc eq "Partly Sunny w/ T-Storms") {
            $icon = " ";
        }
        if ($desc eq "Windy") {
            $icon = " ";
        }
        if ($desc eq "Flurries" || $desc eq "Mostly Cloudy w/ Flurries" || $desc eq "Snow" || $desc eq "Mostly Cloudy w/ Snow") {
            $icron = " ";
        }
        if ($desc eq "Partly Sunny w/ Flurries") {
            $icron = " ";
        }
        if ($desc eq "Ice" || $desc eq "Sleet" || $desc eq "Freezing Rain" || $desc eq "Rain and Snow" || $desc eq "Cold") {
            $icron = " ";
        }
        if ($desc eq "Clear" || $desc eq "Mostly Clear" || $desc eq "Partly Cloudy" || $desc eq "Intermittent Clouds" || $desc eq "Hazy Moonlight") {
            $icron = " ";
        }
        print "$icon$temp";
    }'
