# Backends to disable from all metapac behavior. See the README.md for
# the list of backend names
# Default: []
#disabled_backends = ["apt"]

# Since pacman, pamac, paru, pikaur and yay all operate on the same package database
# they are mutually exclusive and so you must pick which one you want
# metapac to use.
# Must be one of: ["pacman", "pamac", "paru", "pikaur", "yay"]
# Default: "pacman"
arch_package_manager = "yay"

# Since VSCode and VSCodium both operate on the same package database
# they are mutually exclusive and so you must pick which one you want
# metapac to use.
# Must be one of: ["code", "codium"]
# Default: "code"
vscode_variant = "code"

# Whether to default to installing flatpak packages systemwide or for the
# current user. This setting can be overridden on a per-package basis using
# { systemwide = false|true }.
# Default: true
flatpak_default_systemwide = true

# Whether to use the [hostname_groups] config table to decide which
# group files to use or to use all files in the groups folder.
# Default: false
hostname_groups_enabled = true

# Which group files apply for which hostnames
# paths starting without a / are relative to the groups folder
# Default: None
[hostname_groups]
tank = ["base", "system", "x11", "wayland", "window-manager", "xfce", "applications", "utilities", "internet", "development", "emulators", "console-hacks"]
retro = ["base", "system", "x11", "window-manager", "emulators"]
